import type { Issue, Rule, RuleContext, ScanFacts } from '../../types';
import { createRule } from '../rule';
import { computeHeapsExponent, tokenizeIdentifiers } from '@usebrick/engine';
import { getCorpusBaselines } from '../../engine/corpus-baselines';

/**
 * v0.12.1: Heaps-deviation rule (Christ, Bavarian, Koyejo, Lapata 2025,
 * "Zipf's and Heaps' Laws for Tokens and LLM-generated Texts",
 * *EMNLP Findings 2025*).
 *
 * The EMNLP 2025 paper provides peer-reviewed context for vocabulary-growth
 * differences across corpora. This rule is calibrated as source-code hygiene:
 * it fires when a file's vocabulary-growth exponent deviates significantly
 * from the corpus baseline (default 2σ), not as an authorship verdict.
 *
 * **v0.12.1 change**: the baseline is now corpus-derived
 * (`src/engine/corpus-baselines.json` generated by
 * `scripts/compute-corpus-baselines.ts`). v0.12.0 used hardcoded
 * `λ=0.5, σ=0.15`, which was INVERTED on the v6 full-corpus calibration
 * (fired more on human code than on AI).
  * **Peer-reviewed citation:**
 * - Heaps, H. S. (1978), *Information Retrieval: Computational
 *   and Theoretical Aspects*, Academic Press, Ch. 4 — introduces
 *   the vocabulary-growth law |V(t)| = K · t^λ.
 * - Christ, M., Bavarian, A., Koyejo, S., Lapata, M. (2025),
 *   "Zipf's and Heaps' Laws for Tokens and LLM-generated Texts,"
 *   EMNLP Findings 2025. Provides statistical context for Heaps λ;
 *   this rule's calibrated hygiene polarity is not an authorship claim.
 * - v0.12.2 calibration: rule is HYGIENE (lift < 1 in v6) — used
 *   to be reclassified; the math is correct, the AI-vs-source-code
 *   inversion is a property of the corpus, not the method. */
const FALLBACK_LAMBDA_MEAN = 0.5;
const FALLBACK_LAMBDA_STD = 0.15;
const DEVIATION_THRESHOLD_SIGMA = 2;
const MIN_TOKEN_COUNT = 50;

export const heapsDeviationRule = createRule<RuleContext>({
  id: 'logic/heaps-deviation',
  category: 'logic',
  severity: 'medium',
  aiSpecific: false,
  description: 'File vocabulary growth (Heaps λ) deviates significantly from corpus baseline — peer-reviewed source-code hygiene statistic (Christ et al. EMNLP Findings 2025); not an authorship verdict',
  create(context) {
    return context;
  },
  analyze(_context, facts): Issue[] {
    const issues: Issue[] = [];
    if (!facts.v2) return issues;
    const source = facts.v2._source ?? '';
    const tokens = tokenizeIdentifiers(source);
    if (tokens.length < MIN_TOKEN_COUNT) return issues;

    const fit = computeHeapsExponent(tokens);
    if (fit.exponent === 0) return issues;

    // Use corpus-derived baseline if available, else fallback to defaults.
    const baselines = getCorpusBaselines();
    const lambdaMean = baselines?.features.heaps.mean ?? FALLBACK_LAMBDA_MEAN;
    const lambdaStd = baselines?.features.heaps.std ?? FALLBACK_LAMBDA_STD;

    const z = (fit.exponent - lambdaMean) / lambdaStd;
    if (Math.abs(z) < DEVIATION_THRESHOLD_SIGMA) return issues;

    const direction = z > 0 ? 'higher' : 'lower';
    issues.push({
      ruleId: 'logic/heaps-deviation',
      category: 'logic',
      severity: 'medium',
      aiSpecific: false,
      message:
        `Heaps exponent λ=${fit.exponent.toFixed(3)} is ${direction} than corpus baseline ` +
        `(${lambdaMean.toFixed(2)} ± ${lambdaStd.toFixed(2)}, z=${z.toFixed(2)}σ). ` +
        `Per Christ et al. (EMNLP Findings 2025), this vocabulary-growth statistic provides peer-reviewed ` +
        `source-code hygiene context; it is not an authorship verdict or proof of authorship.`,
      line: 1,
      column: 1,
      advice:
        `Review identifier vocabulary and source-code structure: this file's vocabulary ${direction === 'higher' ? 'grows faster' : 'grows slower'} ` +
        `than the calibrated baseline. Check domain naming, generated output, schemas, fixtures, or boilerplate; this hygiene signal ` +
        `is not an authorship verdict or proof of authorship.`,
    });
    return issues;
  },
});

export default heapsDeviationRule satisfies Rule<RuleContext>;
