/**
 * v0.18.4 (Phase B R-M2): types split.
 * Module: baseline
 *
 * Cross-module deps: `Category` + `Severity` from `./primitives`,
 * `Issue` from `./scan`.
 */

import type { Category, Severity } from './primitives';
import type { Issue } from './scan';

export interface BaselineMeta {
  active: boolean;
  version: string;
  baselineRevision: number;
  createdAt: string;
}



export interface BaselineCache {
  version: string;
  config_hash: string;
  git_head: string;
  baseline_created: string;
  baseline_revision: number;
  totalComponentCount: number;
  scores: Record<string, { baselineScore: number; componentCount: number }>;
}



export interface SlopAuditRun {
  timestamp: string;
  version: string;
  slopIndex: number;
  categoryScores: Record<Category, number>;
  topOffenseIds: string[];
  thresholdExceeded: boolean;
}



export interface AutoTunedRule {
  ruleId: string;
  severity: Severity;
  reason: string;
}



export interface RuleSuggestion {
  pattern: string;
  example: string;
  count: number;
  suggestedRuleId: string;
}



/**
 * Optional research/flywheel metrics. Surfaced in the JSON report and the
 * flywheel summary when present. Generated by the
 * `research generate | analyze | candidates` pipeline.
 */
export interface ResearchMetrics {
  generatedSampleCount: number;
  generatedRuleCoverage: number;
  /** Number of fingerprint clusters that turned into candidate rules. */
  candidateYield: number;
  /** When the research artifacts were last refreshed. */
  updatedAt: string;
}



export interface FlywheelState {
  version: string;
  updatedAt: string;
  autoTuned: AutoTunedRule[];
  research?: ResearchMetrics;
}



export interface FlywheelOutput {
  autoTuned: AutoTunedRule[];
  hotspotIssues: Issue[];
  suggestions: RuleSuggestion[];
  research?: ResearchMetrics;
}
