// Auto-generated by scripts/generate-rule-registry.ts. Do not edit manually.
import type { Rule } from '../types';
import { aiAnyDensityRule } from './ai/any-density';
import { aiCommentRatioRule } from './ai/comment-ratio';
import { aiCompressionProfileRule } from './ai/compression-profile';
import { aiConsoleDebugStormRule } from './ai/console-debug-storm';
import { aiDefaultReactStackRule } from './ai/default-react-stack';
import { aiErrorsNearEofRule } from './ai/errors-near-eof';
import { aiFetchDefaultOveruseRule } from './ai/fetch-default-overuse';
import { aiLibraryReinventionRule } from './ai/library-reinvention';
import { aiLogRankHistogramRule } from './ai/log-rank-histogram';
import { aiMarkdownLeakageRule } from './ai/markdown-leakage';
import { aiRenyiProfileRule } from './ai/renyi-profile';
import { aiSegmentSurprisalCvRule } from './ai/segment-surprisal-cv';
import { aiStateDefaultOveruseRule } from './ai/state-default-overuse';
import { aiTailwindColorOveruseRule } from './ai/tailwind-color-overuse';
import { aiTextLikeRatioRule } from './ai/text-like-ratio';
import { aiWhitespaceRegularityRule } from './ai/whitespace-regularity';
import { astroIslandLeakRule } from './arch/astro-island-leak';
import { giantComponentRule } from './component/giant-component';
import { multipleComponentsPerFileRule } from './component/multiple-components-per-file';
import { shadcnPropMismatchRule } from './component/shadcn-prop-mismatch';
import { importPathMismatchRule } from './context/import-path-mismatch';
import { gapMonopolyRule } from './layout/gap-monopoly';
import { mathElementUniformityRule } from './layout/math-element-uniformity';
import { mathGridUniformityRule } from './layout/math-grid-uniformity';
import { spacingGridRule } from './layout/spacing-grid';
import { bayesianConditionalRule } from './logic/bayesian-conditional';
import { boundaryViolationRule } from './logic/boundary-violation';
import { ghostDefensiveRule } from './logic/ghost-defensive';
import { heapsDeviationRule } from './logic/heaps-deviation';
import { keyPropMissingRule } from './logic/key-prop-missing';
import { ksDistributionShiftRule } from './logic/ks-distribution-shift';
import { mathAnyDensityRule } from './logic/math-any-density';
import { mathConsoleLogStormRule } from './logic/math-console-log-storm';
import { mathGiniClassUsageRule } from './logic/math-gini-class-usage';
import { mathVariableNameEntropyRule } from './logic/math-variable-name-entropy';
import { optimisticNoRollbackRule } from './logic/optimistic-no-rollback';
import { qwikHookLeakRule } from './logic/qwik-hook-leak';
import { reactiveHookSoupRule } from './logic/reactive-hook-soup';
import { zipfSlopeAnomalyRule } from './logic/zipf-slope-anomaly';
import { zombieStateRule } from './logic/zombie-state';
import { clsImageRule } from './perf/cls-image';
import { cssBloatRule } from './perf/css-bloat';
import { halsteadAnomalyRule } from './perf/halstead-anomaly';
import { terminologyDriftRule } from './product/terminology-drift';
import { uxPatternFragmentationRule } from './product/ux-pattern-fragmentation';
import { dangerousCorsRule } from './security/dangerous-cors';
import { exposedEnvVarRule } from './security/exposed-env-var';
import { failOpenAuthRule } from './security/fail-open-auth';
import { hardcodedSecretRule } from './security/hardcoded-secret';
import { missingAuthCheckRule } from './security/missing-auth-check';
import { publicAdminRouteRule } from './security/public-admin-route';
import { sqlConstructionRule } from './security/sql-construction';
import { unsafeHtmlRenderRule } from './security/unsafe-html-render';
import { duplicateSetupRule } from './test/duplicate-setup';
import { fakePlaceholderRule } from './test/fake-placeholder';
import { missingEdgeCaseRule } from './test/missing-edge-case';
import { weakAssertionRule } from './test/weak-assertion';
import { calcFontsizeRule } from './typo/calc-fontsize';
import { calcRawPxRule } from './typo/calc-raw-px';
import { clampOffscaleRule } from './typo/clamp-offscale';
import { mathButtonLabelUniformityRule } from './typo/math-button-label-uniformity';
import { mathCtaVocabularyRule } from './typo/math-cta-vocabulary';
import { arbitraryEscapeRule } from './visual/arbitrary-escape';
import { clampSoupRule } from './visual/clamp-soup';
import { forcedLayoutRule } from './visual/forced-layout';
import { genericCenteringRule } from './visual/generic-centering';
import { inlineStyleDominanceRule } from './visual/inline-style-dominance';
import { mathColorClusterRule } from './visual/math-color-cluster';
import { mathDefaultFontRule } from './visual/math-default-font';
import { mathFontEntropyRule } from './visual/math-font-entropy';
import { mathGradientHueRotationRule } from './visual/math-gradient-hue-rotation';
import { mathRoundedEntropyRule } from './visual/math-rounded-entropy';
import { mathSpacingEntropyRule } from './visual/math-spacing-entropy';
import { naturalnessAnomalyRule } from './visual/naturalness-anomaly';
import { radiusScaleViolationRule } from './visual/radius-scale-violation';
import { spacingScaleViolationRule } from './visual/spacing-scale-violation';
import { draggingMovementsRule } from './wcag/dragging-movements';
import { focusAppearanceRule } from './wcag/focus-appearance';
import { focusObscuredRule } from './wcag/focus-obscured';
import { targetSizeRule } from './wcag/target-size';

export const builtinRules: Rule[] = [
  aiAnyDensityRule,
  aiCommentRatioRule,
  aiCompressionProfileRule,
  aiConsoleDebugStormRule,
  aiDefaultReactStackRule,
  aiErrorsNearEofRule,
  aiFetchDefaultOveruseRule,
  aiLibraryReinventionRule,
  aiLogRankHistogramRule,
  aiMarkdownLeakageRule,
  aiRenyiProfileRule,
  aiSegmentSurprisalCvRule,
  aiStateDefaultOveruseRule,
  aiTailwindColorOveruseRule,
  aiTextLikeRatioRule,
  aiWhitespaceRegularityRule,
  astroIslandLeakRule,
  giantComponentRule,
  multipleComponentsPerFileRule,
  shadcnPropMismatchRule,
  importPathMismatchRule,
  gapMonopolyRule,
  mathElementUniformityRule,
  mathGridUniformityRule,
  spacingGridRule,
  bayesianConditionalRule,
  boundaryViolationRule,
  ghostDefensiveRule,
  heapsDeviationRule,
  keyPropMissingRule,
  ksDistributionShiftRule,
  mathAnyDensityRule,
  mathConsoleLogStormRule,
  mathGiniClassUsageRule,
  mathVariableNameEntropyRule,
  optimisticNoRollbackRule,
  qwikHookLeakRule,
  reactiveHookSoupRule,
  zipfSlopeAnomalyRule,
  zombieStateRule,
  clsImageRule,
  cssBloatRule,
  halsteadAnomalyRule,
  terminologyDriftRule,
  uxPatternFragmentationRule,
  dangerousCorsRule,
  exposedEnvVarRule,
  failOpenAuthRule,
  hardcodedSecretRule,
  missingAuthCheckRule,
  publicAdminRouteRule,
  sqlConstructionRule,
  unsafeHtmlRenderRule,
  duplicateSetupRule,
  fakePlaceholderRule,
  missingEdgeCaseRule,
  weakAssertionRule,
  calcFontsizeRule,
  calcRawPxRule,
  clampOffscaleRule,
  mathButtonLabelUniformityRule,
  mathCtaVocabularyRule,
  arbitraryEscapeRule,
  clampSoupRule,
  forcedLayoutRule,
  genericCenteringRule,
  inlineStyleDominanceRule,
  mathColorClusterRule,
  mathDefaultFontRule,
  mathFontEntropyRule,
  mathGradientHueRotationRule,
  mathRoundedEntropyRule,
  mathSpacingEntropyRule,
  naturalnessAnomalyRule,
  radiusScaleViolationRule,
  spacingScaleViolationRule,
  draggingMovementsRule,
  focusAppearanceRule,
  focusObscuredRule,
  targetSizeRule,
];
