import signalStrengthData from './signal-strength.json' with { type: 'json' };
import {
  signalStrengthSchema,
  isDefaultOff,
  type Verdict,
  type SignalStrengthEntry,
} from '@usebrick/core';

/**
 * v0.14.5+: Validate the calibration data at load time. A parse failure
 * means the JSON must be regenerated by the calibration pipeline.
 */
const PARSED = signalStrengthSchema.parse(signalStrengthData);
export const DATA: Record<string, SignalStrengthEntry> = PARSED;

/**
 * Re-export the Verdict type for consumers.
 */
export type { Verdict, SignalStrengthEntry };

export function loadSignalStrength(): Record<string, SignalStrengthEntry> {
  return DATA;
}

export function getSignalStrength(ruleId: string): SignalStrengthEntry | undefined {
  return DATA[ruleId];
}

/**
 * v0.14.5+: The set of rule IDs that should be treated as `'off'` by
 * default. Sourced from:
 *   1. Explicit `defaultOff: true` in signal-strength.json (user opt-in to opt-out)
 *   2. The verdict-based default (NOISY, INVERTED, DORMANT are always opt-out)
 */
export function getDefaultOffRules(): Set<string> {
  const out = new Set<string>();
  for (const [ruleId, strength] of Object.entries(DATA)) {
    if (strength.defaultOff === true) {
      out.add(ruleId);
    } else if (strength.defaultOff === undefined && isDefaultOff(strength.verdict)) {
      out.add(ruleId);
    }
    // defaultOff === false: user explicitly wants the rule enabled (overrides verdict)
  }
  return out;
}

/**
 * Returns true if a rule is a reliable signal — precision above 0.5 AND
 * recall above 0.1. Used by the HTML reporter to color-code badges.
 */
export function isReliableSignal(strength: SignalStrengthEntry | undefined): boolean {
  if (!strength) return true; // unknown → don't flag
  return strength.precision >= 0.5 && strength.recall >= 0.1;
}

export function getAutoDowngrades(
  currentRules: Record<string, 'off' | 'auto' | 'low' | 'medium' | 'high'>,
): Record<string, 'off' | 'low' | 'medium' | 'high'> {
  const downgrades: Record<string, 'off' | 'low' | 'medium' | 'high'> = {};
  for (const [ruleId, strength] of Object.entries(DATA)) {
    if (!isReliableSignal(strength)) {
      const current = currentRules[ruleId];
      const currentSeverity = current ?? 'auto';
      const downgraded = downgradeSeverity(currentSeverity);
      if (downgraded !== currentSeverity) {
        downgrades[ruleId] = downgraded;
      }
    }
  }
  return downgrades;
}

export function downgradeSeverity(s: 'off' | 'auto' | 'low' | 'medium' | 'high'): 'off' | 'low' | 'medium' | 'high' {
  switch (s) {
    case 'high': return 'medium';
    case 'medium': return 'low';
    case 'low': return 'off';
    case 'off': return 'off';
    case 'auto': return 'low';
  }
}
