import signalStrengthData from './signal-strength.json' with { type: 'json' };
import { signalStrengthSchema, isDefaultOff } from '@usebrick/core';
import type { Verdict, SignalStrengthEntry } from '@usebrick/core';

/**
 * v0.14.5+: Validate the calibration data at load time. A parse failure
 * means the JSON must be regenerated by the calibration pipeline.
 *
 * v0.38.x: the calibration pipeline writes a `_v10_1Meta` (and similar
 * `_v*Meta`) provenance row at the top of the JSON — corpus sizes,
 * method, signal distribution. These aren't rule entries; they're
 * calibration metadata. Strip any key starting with `_` before parsing
 * so the Zod schema (which requires `recall`/`fpRate`/`verdict` per row)
 * doesn't reject the whole file and crash the CLI at boot.
 */
const RULE_ENTRIES = Object.fromEntries(
  Object.entries(signalStrengthData).filter(([key]) => !key.startsWith('_')),
);
const PARSED = signalStrengthSchema.parse(RULE_ENTRIES);
export const DATA: Record<string, SignalStrengthEntry> = PARSED;

/**
 * Re-export the Verdict type for consumers.
 */
export type { Verdict, SignalStrengthEntry };

export function loadSignalStrength(): Record<string, SignalStrengthEntry> {
  return DATA;
}

export type HistoricalV101Signal = 'strong' | 'weak' | 'dormant' | 'inverted';

export interface HistoricalSignalStrengthEntry {
  readonly status: 'historical-point-estimate-only';
  readonly dataset: 'v10.1';
  readonly signal: HistoricalV101Signal;
  readonly precision: number;
  readonly recall: number;
  readonly f1: number;
  readonly positiveFires: number;
  readonly negativeFires: number;
}

export interface HistoricalSignalStrengthTable {
  readonly status: 'historical-point-estimate-only';
  readonly dataset: 'v10.1';
  readonly entries: Readonly<Record<string, HistoricalSignalStrengthEntry>>;
}

const HISTORICAL_V10_1_RULE_COUNT = 103;
const HISTORICAL_V10_1_SIGNALS = new Set<HistoricalV101Signal>([
  'strong', 'weak', 'dormant', 'inverted',
]);

function historicalV101Entry(
  ruleId: string,
  raw: Record<string, unknown>,
): HistoricalSignalStrengthEntry | undefined {
  const fields = [
    '_v10_1Signal', '_v10_1Precision', '_v10_1Recall', '_v10_1F1',
    '_v10_1PositiveFires', '_v10_1NegativeFires',
  ] as const;
  if (fields.every((field) => raw[field] === undefined)) return undefined;
  const signal = raw._v10_1Signal;
  const rates = [raw._v10_1Precision, raw._v10_1Recall, raw._v10_1F1];
  const counts = [raw._v10_1PositiveFires, raw._v10_1NegativeFires];
  if (typeof signal !== 'string' || !HISTORICAL_V10_1_SIGNALS.has(signal as HistoricalV101Signal)
    || rates.some((value) => typeof value !== 'number' || !Number.isFinite(value) || value < 0 || value > 1)
    || counts.some((value) => !Number.isSafeInteger(value) || (value as number) < 0)) {
    throw new TypeError(`Historical v10.1 signal entry is invalid for ${ruleId}`);
  }
  return Object.freeze({
    status: 'historical-point-estimate-only',
    dataset: 'v10.1',
    signal: signal as HistoricalV101Signal,
    precision: rates[0] as number,
    recall: rates[1] as number,
    f1: rates[2] as number,
    positiveFires: counts[0] as number,
    negativeFires: counts[1] as number,
  });
}

const HISTORICAL_V10_1_ENTRIES = Object.freeze(Object.fromEntries(
  Object.entries(RULE_ENTRIES).flatMap(([ruleId, value]) => {
    const entry = historicalV101Entry(ruleId, value as Record<string, unknown>);
    return entry === undefined ? [] : [[ruleId, entry] as const];
  }),
));
if (Object.keys(HISTORICAL_V10_1_ENTRIES).length !== HISTORICAL_V10_1_RULE_COUNT) {
  throw new TypeError(`Historical v10.1 signal table must contain exactly ${HISTORICAL_V10_1_RULE_COUNT} rows`);
}

const HISTORICAL_SIGNAL_STRENGTH: HistoricalSignalStrengthTable = Object.freeze({
  status: 'historical-point-estimate-only',
  dataset: 'v10.1',
  entries: HISTORICAL_V10_1_ENTRIES,
});

/**
 * Names the authority boundary around the shipped signal table and exposes a
 * read-only view. These values are useful historical point estimates; they
 * are not current policy, current quality authority, or authorship evidence.
 */
export function loadHistoricalSignalStrength(): HistoricalSignalStrengthTable {
  return HISTORICAL_SIGNAL_STRENGTH;
}

export function getSignalStrength(ruleId: string): SignalStrengthEntry | undefined {
  return DATA[ruleId];
}

/**
 * v0.14.5+: The set of rule IDs that should be treated as `'off'` by
 * default. Sourced from:
 *   1. Explicit `defaultOff: true` in signal-strength.json (user opt-in to opt-out)
 *   2. The verdict-based default (NOISY, INVERTED, DORMANT are always opt-out)
 */
export function getDefaultOffRules(): Set<string> {
  const out = new Set<string>();
  for (const [ruleId, strength] of Object.entries(DATA)) {
    if (strength.defaultOff === true) {
      out.add(ruleId);
    } else if (strength.defaultOff === undefined && isDefaultOff(strength.verdict)) {
      out.add(ruleId);
    }
    // defaultOff === false: user explicitly wants the rule enabled (overrides verdict)
  }
  return out;
}

/**
 * Returns true if a rule is a reliable signal — precision above 0.5 AND
 * recall above 0.1. Used by the HTML reporter to color-code badges.
 */
export function isReliableSignal(strength: SignalStrengthEntry | undefined): boolean {
  if (!strength) return true; // unknown → don't flag
  return strength.precision >= 0.5 && strength.recall >= 0.1;
}

export function getAutoDowngrades(
  currentRules: Record<string, 'off' | 'auto' | 'low' | 'medium' | 'high'>,
): Record<string, 'off' | 'low' | 'medium' | 'high'> {
  const downgrades: Record<string, 'off' | 'low' | 'medium' | 'high'> = {};
  for (const [ruleId, strength] of Object.entries(DATA)) {
    if (!isReliableSignal(strength)) {
      const current = currentRules[ruleId];
      const currentSeverity = current ?? 'auto';
      const downgraded = downgradeSeverity(currentSeverity);
      if (downgraded !== currentSeverity) {
        downgrades[ruleId] = downgraded;
      }
    }
  }
  return downgrades;
}

export function downgradeSeverity(s: 'off' | 'auto' | 'low' | 'medium' | 'high'): 'off' | 'low' | 'medium' | 'high' {
  switch (s) {
    case 'high': return 'medium';
    case 'medium': return 'low';
    case 'low': return 'off';
    case 'off': return 'off';
    case 'auto': return 'low';
  }
}
