type Status = 'success_findings'|'success_zero'|'excluded'|'parse_failure'|'timeout'|'scanner_failure';
const STATUSES = new Set<Status>(['success_findings','success_zero','excluded','parse_failure','timeout','scanner_failure']);
const FAILURES = new Set<Status>(['parse_failure','timeout','scanner_failure']);
function obj(v: unknown): v is Record<string, unknown> { return typeof v === 'object' && v !== null && !Array.isArray(v); }
function str(v: unknown): v is string { return typeof v === 'string' && v.length > 0; }
function int(v: unknown): v is number { return typeof v === 'number' && Number.isSafeInteger(v) && v >= 0; }
function keys(v: Record<string,unknown>, allowed: string[]): boolean { return Object.keys(v).every(k=>allowed.includes(k)); }
export function isCalibrationObservationV103(v: unknown): boolean { if(!obj(v)||!keys(v,['version','runId','fileId','language','polarity','status','findingsCount','exclusionReason','failureCode'])||v.version!=='v10.3'||!str(v.runId)||!str(v.fileId)||!str(v.language)||!(v.polarity==='verified_ai'||v.polarity==='verified_human')||!STATUSES.has(v.status as Status))return false; const s=v.status as Status; return (s==='success_findings'?int(v.findingsCount)&&v.findingsCount>0:s==='success_zero'?v.findingsCount===0:s==='excluded'?str(v.exclusionReason):FAILURES.has(s)&&str(v.failureCode)); }
export function isCalibrationFailureV103(v: unknown): boolean { return obj(v)&&keys(v,['version','runId','fileId','status','failureCode'])&&v.version==='v10.3'&&str(v.runId)&&str(v.fileId)&&FAILURES.has(v.status as Status)&&str(v.failureCode); }
export function isCalibrationCoverageV103(v: unknown): boolean { return obj(v)&&keys(v,['version','runId','requested','successful','excluded','failed','strata'])&&v.version==='v10.3'&&str(v.runId)&&int(v.requested)&&int(v.successful)&&int(v.excluded)&&int(v.failed)&&v.requested===v.successful+v.excluded+v.failed&&Array.isArray(v.strata)&&v.strata.every(s=>obj(s)&&keys(s,['language','polarity','requested','successful','excluded','failed'])&&str(s.language)&&(s.polarity==='verified_ai'||s.polarity==='verified_human')&&int(s.requested)&&int(s.successful)&&int(s.excluded)&&int(s.failed)&&s.requested===s.successful+s.excluded+s.failed); }
