type Status = 'success_findings'|'success_zero'|'excluded'|'parse_failure'|'timeout'|'scanner_failure';
const STATUSES = new Set<Status>(['success_findings','success_zero','excluded','parse_failure','timeout','scanner_failure']);
const FAILURES = new Set<Status>(['parse_failure','timeout','scanner_failure']);
const EVIDENCE_SEVERITIES = new Set(['low','medium','high']);
const EVIDENCE_CATEGORIES = new Set(['visual','typo','wcag','layout','component','logic','arch','perf','security','test','docs','db','ai','context','product','i18n']);
const EVIDENCE_RULE_ID = /^[A-Za-z0-9][A-Za-z0-9._/-]*$/;
type EvidenceCategory = 'visual'|'typo'|'wcag'|'layout'|'component'|'logic'|'arch'|'perf'|'security'|'test'|'docs'|'db'|'ai'|'context'|'product'|'i18n';
export type CalibrationRuleEvidenceV103 = { ruleId: string; category: EvidenceCategory; aiSpecific: boolean; severity: 'low'|'medium'|'high'; count: number };
function obj(v: unknown): v is Record<string, unknown> { return typeof v === 'object' && v !== null && !Array.isArray(v); }
function str(v: unknown): v is string { return typeof v === 'string' && v.length > 0; }
function int(v: unknown): v is number { return typeof v === 'number' && Number.isSafeInteger(v) && v >= 0; }
function keys(v: Record<string,unknown>, allowed: string[]): boolean { return Object.keys(v).every(k=>allowed.includes(k)); }
export function isCalibrationRuleEvidenceV103(v: unknown): v is CalibrationRuleEvidenceV103 { return obj(v)&&keys(v,['ruleId','category','aiSpecific','severity','count'])&&str(v.ruleId)&&EVIDENCE_RULE_ID.test(v.ruleId)&&typeof v.aiSpecific==='boolean'&&typeof v.category==='string'&&EVIDENCE_CATEGORIES.has(v.category)&&EVIDENCE_SEVERITIES.has(v.severity as string)&&int(v.count)&&v.count>0; }
export function isCalibrationRuleEvidenceListV103(v: unknown): v is CalibrationRuleEvidenceV103[] { if(!Array.isArray(v))return false; const seen=new Set<string>(); for(const item of v){ if(!isCalibrationRuleEvidenceV103(item)||seen.has(item.ruleId))return false; seen.add(item.ruleId); } return true; }
export function isCalibrationObservationV103(v: unknown): boolean { if(!obj(v)||!keys(v,['version','runId','fileId','repositoryId','familyId','language','polarity','status','findingsCount','exclusionReason','failureCode','ruleEvidence'])||v.version!=='v10.3'||!str(v.runId)||!str(v.fileId)||!str(v.repositoryId)||!str(v.familyId)||!str(v.language)||!(v.polarity==='verified_ai'||v.polarity==='verified_human')||!STATUSES.has(v.status as Status))return false; const s=v.status as Status; const evidenceOk=v.ruleEvidence===undefined||isCalibrationRuleEvidenceListV103(v.ruleEvidence); const evidenceMatchesCount=v.ruleEvidence===undefined||(evidenceOk&&v.findingsCount===([...v.ruleEvidence as CalibrationRuleEvidenceV103[]].reduce((sum,item)=>sum+item.count,0))); return (s==='success_findings'?int(v.findingsCount)&&v.findingsCount>0&&v.exclusionReason===undefined&&v.failureCode===undefined&&evidenceMatchesCount:s==='success_zero'?v.findingsCount===0&&v.exclusionReason===undefined&&v.failureCode===undefined&&v.ruleEvidence===undefined:s==='excluded'?str(v.exclusionReason)&&v.findingsCount===undefined&&v.failureCode===undefined&&v.ruleEvidence===undefined:FAILURES.has(s)&&str(v.failureCode)&&v.findingsCount===undefined&&v.exclusionReason===undefined&&v.ruleEvidence===undefined); }
export function isCalibrationFailureV103(v: unknown): boolean { return obj(v)&&keys(v,['version','runId','fileId','status','failureCode'])&&v.version==='v10.3'&&str(v.runId)&&str(v.fileId)&&FAILURES.has(v.status as Status)&&str(v.failureCode); }
export function isCalibrationCoverageV103(v: unknown): boolean { const roll=(x:unknown,key:string)=>Array.isArray(x)&&x.every(r=>obj(r)&&keys(r,[key,'requested','successful','excluded','failed'])&&str(r[key])&&int(r.requested)&&int(r.successful)&&int(r.excluded)&&int(r.failed)&&r.requested===r.successful+r.excluded+r.failed); return obj(v)&&keys(v,['version','runId','requested','successful','excluded','failed','strata','repositories','families'])&&v.version==='v10.3'&&str(v.runId)&&int(v.requested)&&int(v.successful)&&int(v.excluded)&&int(v.failed)&&v.requested===v.successful+v.excluded+v.failed&&Array.isArray(v.strata)&&v.strata.every(s=>obj(s)&&keys(s,['language','polarity','requested','successful','excluded','failed'])&&str(s.language)&&(s.polarity==='verified_ai'||s.polarity==='verified_human')&&int(s.requested)&&int(s.successful)&&int(s.excluded)&&int(s.failed)&&s.requested===s.successful+s.excluded+s.failed)&&roll(v.repositories,'repositoryId')&&roll(v.families,'familyId'); }
