import { z } from 'zod';
import { VERDICTS } from './verdicts';

/**
 * v0.14.5+: Zod schema for the signal-strength.json shape.
 * Used by slopbrick to validate the calibration data at load time.
 * A parse failure throws a contract violation, which means the JSON
 * must be regenerated by the calibration pipeline.
 */
export const signalStrengthSchema = z.record(
  z.string(), // ruleId
  z.object({
    recall: z.number().min(0).max(1),
    fpRate: z.number().min(0).max(1),
    ratio: z.number(),
    precision: z.number().min(0).max(1),
    lastCalibratedAt: z.string().datetime(),
    verdict: z.enum(VERDICTS),
    // defaultOff is opt-in per-rule. Absent = the rule follows
    // isDefaultOff(verdict). Present (true or false) = user override.
    defaultOff: z.boolean().optional(),
    // aiSpecific is opt-in. Absent = derived from verdict
    // (USEFUL/OK → true, others → false) in loadSignals().
    // Present (true or false) = user override. v0.17.1: added to
    // the Zod schema so .parse() no longer strips the field.
    aiSpecific: z.boolean().optional(),
  }),
);

export type SignalStrengthEntry = z.infer<typeof signalStrengthSchema>[string];
