import { z } from 'zod';
import { VERDICTS } from './verdicts';

/**
 * v0.14.5+: Zod schema for the signal-strength.json shape.
 * Used by slopbrick to validate the calibration data at load time.
 * A parse failure throws a contract violation, which means the JSON
 * must be regenerated by the calibration pipeline.
 *
 * v0.17.3 (B5): added `aiSpecific: z.boolean().optional()`. Without
 * it, Zod's `.parse()` strips the field — even if a rule has
 * `aiSpecific: true` in signal-strength.json, the engine never
 * sees it, every LLR is 0, and the composite probability collapses
 * to the constant prior (0.428). This field marks rules whose
 * signal is *specific* to AI generation patterns (vs. general
 * code quality), so they get full weight in the composite score.
 */
export const signalStrengthSchema = z.record(
  z.string(), // ruleId
  z.object({
    recall: z.number().min(0).max(1),
    fpRate: z.number().min(0).max(1),
    ratio: z.number(),
    precision: z.number().min(0).max(1),
    lastCalibratedAt: z.string().datetime(),
    verdict: z.enum(VERDICTS),
    // defaultOff is opt-in per-rule. Absent = the rule follows
    // isDefaultOff(verdict). Present (true or false) = user override.
    defaultOff: z.boolean().optional(),
    // v0.17.3 (B5): mark rules whose signal is specific to AI
    // generation. Without this field, the composite scoring pipeline
    // can't distinguish "this rule fires on AI slop" from "this rule
    // fires on sloppy code in general" — and gives zero weight to
    // both. See packages/engine/src/composite-scoring.ts:136,164.
    aiSpecific: z.boolean().optional(),
  }),
);

export type SignalStrengthEntry = z.infer<typeof signalStrengthSchema>[string];
