#!/usr/bin/env node
/**
 * v0.36.0: Merge the v10-signal-strength.json (generated by
 * calibrate.mjs) into the main src/rules/signal-strength.json.
 *
 * For each rule present in v10:
 *   - Add _v10* fields (kept as-is)
 *   - If the rule has no v10* fields yet, add them
 *   - If _v10Verdict is STRONG_POSITIVE or WEAK_POSITIVE,
 *     update the main verdict to OK (was DORMANT)
 *   - Update precision/recall/ratio with v10 numbers
 *     (these replace v9 era-confounded estimates)
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const V10_FILE = join(__dirname, 'v10-signal-strength.json');
const MAIN_FILE = join(__dirname, '..', '..', '..', 'src', 'rules', 'signal-strength.json');

const v10 = JSON.parse(readFileSync(V10_FILE, 'utf8'));
const main = JSON.parse(readFileSync(MAIN_FILE, 'utf8'));

let updated = 0, added = 0, unchanged = 0;
for (const [ruleId, v10Stats] of Object.entries(v10)) {
  if (!(ruleId in main)) {
    // New rule — add a full entry
    main[ruleId] = v10Stats;
    added++;
    continue;
  }
  // Merge _v10* fields into existing entry
  const m = main[ruleId];
  for (const k of Object.keys(v10Stats)) {
    m[k] = v10Stats[k];
  }
  // Update main verdict if v10 has a strong signal
  if (v10Stats._v10Verdict === 'STRONG_POSITIVE' || v10Stats._v10Verdict === 'WEAK_POSITIVE') {
    m.verdict = 'OK';
    m.aiSpecific = true;
  }
  // Use v10 numbers as the new headline precision/recall/ratio
  m.recall = v10Stats._v10Recall;
  m.fpRate = v10Stats._v10Lift > 0 ? 1 / v10Stats._v10Lift : 0;
  m.ratio = v10Stats._v10Lift;
  m.precision = v10Stats._v10Precision;
  m.lastCalibratedAt = new Date().toISOString().slice(0, 10) + 'T00:00:00Z';
  updated++;
}

writeFileSync(MAIN_FILE, JSON.stringify(main, null, 2) + '\n');
console.log(`Merged v10 → main signal-strength.json`);
console.log(`  ${added} new rules added`);
console.log(`  ${updated} existing rules updated with _v10* fields`);
console.log(`  Total rules in main: ${Object.keys(main).length}`);

// Summary of v10 verdicts
const verdicts = {};
for (const s of Object.values(v10)) {
  verdicts[s._v10Verdict] = (verdicts[s._v10Verdict] ?? 0) + 1;
}
console.log(`\nv10 verdict distribution:`);
for (const [v, n] of Object.entries(verdicts).sort((a, b) => b[1] - a[1])) {
  console.log(`  ${v.padEnd(20)} ${n}`);
}
