/**
 * Generates src/rules/builtins.ts from rule modules found in src/rules category folders.
 *
 * Run with: pnpm generate:rules
 */
import { readdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const RULES_DIR = path.resolve(__dirname, '../src/rules');
const OUTPUT_FILE = path.resolve(__dirname, '../src/rules/builtins.ts');

interface RuleModule {
  category: string;
  file: string;
  name: string;
}

async function discoverRuleModules(): Promise<RuleModule[]> {
  const entries = await readdir(RULES_DIR, { withFileTypes: true });
  const categories = entries
    .filter((e) => e.isDirectory())
    .map((e) => e.name)
    .sort();

  const modules: RuleModule[] = [];

  for (const category of categories) {
    const categoryDir = path.join(RULES_DIR, category);
    const files = (await readdir(categoryDir))
      .filter((f) => f.endsWith('.ts') && !f.endsWith('.test.ts'))
      .sort();

    for (const file of files) {
      // Skip files that don't define a rule — utility files like `utils.ts`
      // are part of the category's toolbox but aren't rules themselves.
      if (file === 'utils.ts' || file.endsWith('.utils.ts')) continue;
      const filePath = path.join(categoryDir, file);
      const content = await readFile(filePath, 'utf8');
      const match = content.match(/export\s+const\s+(\w+Rule)\b/);
      if (!match) {
        throw new Error(
          `Could not find an exported rule in ${path.join(category, file)}. ` +
            `Rule files must export a const ending in "Rule" (e.g. export const myRule = ...).`,
        );
      }
      modules.push({ category, file: file.replace(/\.ts$/, ''), name: match[1] });
    }
  }

  return modules.sort((a, b) => `${a.category}/${a.file}`.localeCompare(`${b.category}/${b.file}`));
}

function render(modules: RuleModule[]): string {
  const imports = modules
    .map((m) => `import { ${m.name} } from './${m.category}/${m.file}';`)
    .join('\n');

  const arrayItems = modules.map((m) => `  ${m.name},`).join('\n');

  return `// Auto-generated by scripts/generate-rule-registry.ts. Do not edit manually.
import type { Rule } from '../types';
${imports}

export const builtinRules: Rule[] = [
${arrayItems}
];
`;
}

async function main() {
  const modules = await discoverRuleModules();
  const output = render(modules);
  await writeFile(OUTPUT_FILE, output, 'utf8');
  console.log(`Generated ${OUTPUT_FILE} with ${modules.length} rule(s).`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
