/**
 * Generates src/rules/builtins.ts from rule modules found in src/rules category folders.
 *
 * Run with: pnpm generate:rules
 *
 * --check mode: compare the would-be output against the existing file and exit
 * non-zero on diff. Wire this into CI to catch the "added a rule, forgot to
 * regenerate" path with a loud, fast, locally-runnable failure.
 */
import { existsSync } from 'node:fs';
import { readdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const RULES_DIR = path.resolve(__dirname, '../src/rules');
const OUTPUT_FILE = path.resolve(__dirname, '../src/rules/builtins.ts');

interface RuleModule {
  category: string;
  file: string;
  name: string;
  /** Extracted from the `id:` field on the rule, used for duplicate detection. */
  id: string;
}

async function discoverRuleModules(): Promise<RuleModule[]> {
  const entries = await readdir(RULES_DIR, { withFileTypes: true });
  const categories = entries
    .filter((e) => e.isDirectory())
    .map((e) => e.name)
    .sort();

  const modules: RuleModule[] = [];

  for (const category of categories) {
    const categoryDir = path.join(RULES_DIR, category);
    const files = (await readdir(categoryDir))
      .filter((f) => f.endsWith('.ts') && !f.endsWith('.test.ts'))
      .sort();

    for (const file of files) {
      // Skip files that don't define a rule — utility files like `utils.ts`
      // are part of the category's toolbox but aren't rules themselves.
      // `index.ts` files are barrel re-exports (e.g. `dead/index.ts`); skip
      // them too so the generator doesn't trip on the category index.
      if (file === 'utils.ts' || file.endsWith('.utils.ts') || file === 'index.ts') continue;
      const filePath = path.join(categoryDir, file);
      const content = await readFile(filePath, 'utf8');
      const match = content.match(/export\s+const\s+(\w+Rule)\b/);
      if (!match) {
        throw new Error(
          `Could not find an exported rule in ${path.join(category, file)}. ` +
            `Rule files must export a const ending in "Rule" (e.g. export const myRule = ...).`,
        );
      }
      const idMatch = content.match(/\bid:\s*['"]([^'"]+)['"]/);
      if (!idMatch) {
        throw new Error(
          `Could not find an \`id: '...'\` field in ${path.join(category, file)}. ` +
            `Rule files must declare their id (e.g. id: 'security/my-rule').`,
        );
      }
      modules.push({
        category,
        file: file.replace(/\.ts$/, ''),
        name: match[1],
        id: idMatch[1],
      });
    }
  }

  // Duplicate-id detection: every rule id must be unique. Two rules with
  // the same id would silently overwrite each other in `RuleRegistry.set`,
  // masking the second rule entirely. Fail loudly at generation time
  // instead of at runtime.
  const byId = new Map<string, RuleModule[]>();
  for (const m of modules) {
    const existing = byId.get(m.id) ?? [];
    existing.push(m);
    byId.set(m.id, existing);
  }
  for (const [id, owners] of byId) {
    if (owners.length > 1) {
      const paths = owners.map((o) => path.join(o.category, o.file + '.ts')).join(', ');
      throw new Error(
        `Rule id "${id}" is defined in multiple files: ${paths}. ` +
          `Rule ids must be unique.`,
      );
    }
  }

  return modules.sort((a, b) => `${a.category}/${a.file}`.localeCompare(`${b.category}/${b.file}`));
}

function render(modules: RuleModule[]): string {
  const imports = modules
    .map((m) => `import { ${m.name} } from './${m.category}/${m.file}';`)
    .join('\n');

  const arrayItems = modules.map((m) => `  ${m.name},`).join('\n');

  return `// Auto-generated by scripts/generate-rule-registry.ts. Do not edit manually.
import type { Rule } from '../types';
${imports}

export const builtinRules: Rule[] = [
${arrayItems}
];
`;
}

async function main() {
  const checkMode = process.argv.includes('--check');

  const modules = await discoverRuleModules();
  const output = render(modules);

  if (checkMode) {
    if (!existsSync(OUTPUT_FILE)) {
      console.error(`❌ ${OUTPUT_FILE} does not exist.`);
      console.error(`   Run \`pnpm generate:rules\` to create it, then commit.`);
      process.exit(1);
    }
    const existing = await readFile(OUTPUT_FILE, 'utf8');
    if (existing !== output) {
      console.error(`❌ ${path.relative(process.cwd(), OUTPUT_FILE)} is out of sync with src/rules/.`);
      console.error(`   Run \`pnpm generate:rules\` and commit the result.`);
      console.error(`   (${modules.length} rule(s) discovered; existing file has different content.)`);
      process.exit(1);
    }
    console.log(`✓ ${path.relative(process.cwd(), OUTPUT_FILE)} is in sync (${modules.length} rule(s)).`);
    return;
  }

  await writeFile(OUTPUT_FILE, output, 'utf8');
  console.log(`Generated ${OUTPUT_FILE} with ${modules.length} rule(s).`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
