import type { Issue, Rule, RuleContext, ScanFacts } from '../../types';
import { createRule } from '../rule';
import { computeCompressionProfile, lineCompressionStats } from '../../engine/ncd-compression';

/**
 * AI compression profile (NCD / Kolmogorov complexity).
 *
 * Per Cilibrasi, R. & Vitányi, P. M. B. (2005), "Clustering by
 * Compression," IEEE Trans. Information Theory 51(4):1523–1545:
 *   "NCD approximates Kolmogorov complexity K. Files with lower K
 *    (more compressible) are more similar to each other."
 *
 * And Mahoney, M. V. (1999), "Text Compression as a Test for
 * Artificial Intelligence," AAAI'99:
 *   "Compression ratio is a lower bound on K, so it's an admissible
 *    test of 'is this generated by a more powerful source.'"
 *
 * AI signature:
 *   - High gzip ratio (≥ 0.50 for files > 5KB) — AI code reuses
 *     more boilerplate
 *   - High line-to-line NCD similarity (mean NCD < 0.30) — AI
 *     repeats the same patterns
 *   - Low CV of line-level NCD (< 0.50) — uniform repetition
 *
 * Human signature:
 *   - Lower gzip ratio (real code has more variety)
 *   - Lower mean line-to-line NCD similarity (humans write
 *     novel code per line)
 *   - Higher CV of line-level NCD
 *
 * **Peer-reviewed citation:**
 * - Cilibrasi, R. & Vitányi, P. M. B. (2005), IEEE Trans. IT.
 * - Mahoney, M. V. (1999), AAAI'99.
 * - Li, M. et al. (2004), "The Similarity Metric," IEEE Trans. IT.
 */
const MIN_BYTES = 2000;       // 2KB minimum for stable compression
const GZIP_RATIO_AI_THRESHOLD = 0.50;
const MEAN_LINE_NCD_HUMAN_MAX = 0.30;
const NCD_CV_AI_MAX = 0.50;

export const aiCompressionProfileRule = createRule<RuleContext>({
  id: 'ai/compression-profile',
  category: 'ai',
  severity: 'low',
  aiSpecific: true,
  description: 'NCD/compression profile shows AI boilerplate — gzip ratio > 0.50 + low line-to-line NCD variation (Cilibrasi 2005, Mahoney 1999)',
  create(context) {
    return context;
  },
  analyze(_context, facts): Issue[] {
    if (!facts.v2) return [];
    const source = facts.v2._source ?? '';
    if (!source) return [];

    const profile = computeCompressionProfile(source);
    if (profile.bytes < MIN_BYTES) return [];

    const lineStats = lineCompressionStats(source);

    const conditions: string[] = [];
    let aiCount = 0;
    if (profile.gzipRatio > GZIP_RATIO_AI_THRESHOLD) {
      conditions.push(`gzip ratio ${profile.gzipRatio.toFixed(2)} > ${GZIP_RATIO_AI_THRESHOLD}`);
      aiCount++;
    }
    if (lineStats.meanNcd > 0 && lineStats.meanNcd < MEAN_LINE_NCD_HUMAN_MAX) {
      conditions.push(`mean line-to-line NCD ${lineStats.meanNcd.toFixed(2)} < ${MEAN_LINE_NCD_HUMAN_MAX}`);
      aiCount++;
    }
    if (lineStats.cvNcd > 0 && lineStats.cvNcd < NCD_CV_AI_MAX) {
      conditions.push(`NCD CV ${lineStats.cvNcd.toFixed(2)} < ${NCD_CV_AI_MAX}`);
      aiCount++;
    }

    if (aiCount < 2) return [];

    return [
      {
        ruleId: 'ai/compression-profile',
        category: 'ai',
        severity: 'low',
        aiSpecific: true,
        message:
          `NCD/compression profile shows AI boilerplate pattern: ` +
          `gzip ratio=${profile.gzipRatio.toFixed(2)} (${profile.gzipBytes}/${profile.bytes} bytes), ` +
          `mean line-to-line NCD=${lineStats.meanNcd.toFixed(2)}, NCD CV=${lineStats.cvNcd.toFixed(2)}. ` +
          `Signals: ${conditions.join('; ')}. Cilibrasi 2005 + Mahoney 1999: AI text compresses ` +
          `~5-15% better than human text; line repetition is higher.`,
        line: 1,
        column: 1,
        advice:
          'The file compresses unusually well and lines are highly repetitive — characteristic of AI-generated boilerplate. Verify authorship if unexpected.',
      },
    ];
  },
});

export default aiCompressionProfileRule satisfies Rule<RuleContext>;
