// Per-target AI agent snippet generators.
//
// Each function returns the file content for one agent's directive
// file. Composition:
//
//   - generateCursorSnippet — bespoke layout with ## Verification footer
//     (the only target that doesn't go through baseContent).
//
//   - generateAgentsMdSnippet / generateClaudeMdSnippet — baseContent +
//     a "## How to verify" / "## Verification" footer. AGENTS.md and
//     CLAUDE.md have evolved to need a closing pointer to the scanner.
//
//   - generateAiderSnippet / generateWindsurfSnippet /
//     generateClineRules / generateCursorrulesLegacySnippet /
//     generateGeminiSnippet / generateCopilotSnippet — straight
//     baseContent calls with tool-specific title + intro. Their only
//     differentiation is the label and how the file path is documented.
//
// The target registry that maps each function to a CLI flag, file
// path, and human-readable agent name lives in ./targets.ts.

import type { Rule } from '../types.js';
import { CATEGORY_DIRECTIVES, RULE_HINTS } from './data.js';
import { aiSpecificRules, categorizeRules, baseContent } from './render.js';

export function generateCursorSnippet(rules: Rule[]): string {
  const lines: string[] = [];
  lines.push('# slopbrick cursor rules');
  lines.push('');
  lines.push('Generated by `slopbrick init --cursor`. These rules describe patterns that slopbrick');
  lines.push('flags as AI-generated frontend slop. Avoid them when writing code in this project.');
  lines.push('');
  lines.push('## Category-level directives');
  lines.push('');
  for (const [category, directive] of Object.entries(CATEGORY_DIRECTIVES)) {
    lines.push('- **' + category + '**: ' + directive);
  }
  lines.push('');
  lines.push('## Per-rule directives');
  lines.push('');
  const ai = aiSpecificRules(rules);
  const byCategory = categorizeRules(ai);
  for (const [category, list] of byCategory) {
    lines.push('### ' + category);
    lines.push('');
    for (const rule of list) {
      const hint = RULE_HINTS[rule.id] ?? 'Avoid patterns that fire rule `' + rule.id + '`.';
      lines.push('- **`' + rule.id + '`** (' + rule.severity + '): ' + hint);
    }
    lines.push('');
  }
  lines.push('## Verification');
  lines.push('');
  lines.push('After writing code, run `slopbrick scan` and check for issues in any of the categories above.');
  lines.push('Use `slopbrick fix` for auto-fixable rules. Use `slopbrick mcp` from MCP-aware clients to query rules and scan files programmatically.');
  lines.push('');
  return lines.join('\n');
}

export function generateAgentsMdSnippet(rules: Rule[]): string {
  return baseContent(
    rules,
    'AGENTS.md',
    'Generated by `slopbrick init --agents-md`. Read these directives when writing or modifying code in this project. AGENTS.md is the de facto standard read by OpenAI Codex, opencode, Pi, Cline, Continue, Gemini, Claude Code (fallback), and others.',
  ) + '## How to verify\n\nAfter editing code, run `slopbrick scan`. Any issue with a category in this file is something to fix.\n';
}

export function generateClaudeMdSnippet(rules: Rule[]): string {
  return baseContent(
    rules,
    'CLAUDE.md',
    'Generated by `slopbrick init --claude-md`. Read this file at the start of every Claude Code session in this project. CLAUDE.md takes precedence over AGENTS.md for Claude Code.',
  ) + '## Verification\n\nRun `slopbrick scan` after edits. If MCP is configured (`slopbrick mcp`), use `slop_scan_file` proactively to check before reporting code as done.\n';
}

export function generateAiderSnippet(rules: Rule[]): string {
  return baseContent(
    rules,
    'CONVENTIONS.md',
    'Generated by `slopbrick init --aider`. Aider reads CONVENTIONS.md (not AGENTS.md) for project conventions.',
  );
}

export function generateWindsurfSnippet(rules: Rule[]): string {
  return baseContent(
    rules,
    '.windsurfrules',
    'Generated by `slopbrick init --windsurf`. Windsurf Cascade reads .windsurfrules at project root.',
  );
}

export function generateClineRules(rules: Rule[]): string {
  // Cline uses .clinerules/ folder with one or more AGENTS.md inside.
  // Return a single file content (caller decides the path).
  return baseContent(
    rules,
    'AGENTS.md',
    'Generated by `slopbrick init --cline`. Cline reads .clinerules/AGENTS.md from the project root.',
  );
}

export function generateCursorrulesLegacySnippet(rules: Rule[]): string {
  // Legacy Cursor format. Flat single-file rule list.
  return baseContent(
    rules,
    '.cursorrules',
    'Generated by `slopbrick init --cursorrules`. This is the legacy Cursor rule format. Prefer `.cursor/rules/slopbrick.mdc` (use --cursor) for new projects.',
  );
}

export function generateGeminiSnippet(rules: Rule[]): string {
  return baseContent(
    rules,
    'GEMINI.md',
    'Generated by `slopbrick init --gemini`. Gemini CLI reads .gemini/GEMINI.md from project root.',
  );
}

export function generateCopilotSnippet(rules: Rule[]): string {
  return baseContent(
    rules,
    'copilot-instructions.md',
    'Generated by `slopbrick init --copilot`. GitHub Copilot reads .github/copilot-instructions.md from project root.',
  );
}