/**
 * v0.12.1: Corpus-derived baselines for the 3 calibration rules
 * (heaps-deviation, zipf-slope-anomaly, ks-distribution-shift).
 *
 * The 3 rules shipped with hardcoded baselines (λ=0.5, s=1.0, fixed
 * reference vectors) in v0.12.0. On the v6 full-corpus calibration, all 3
 * turned out to be INVERTED — they fired more on human code than on AI
 * code, because the baselines didn't match the actual corpus.
 *
 * `src/engine/corpus-baselines.json` is generated by
 * `scripts/compute-corpus-baselines.ts` from the v6 corpus and read at
 * module load. If the JSON is missing, the rules fall back to the
 * v0.12.0 hardcoded defaults (with a warning).
 */
import baselineData from './corpus-baselines.json' with { type: 'json' };

export interface CorpusBaselines {
  version: number;
  generatedAt: string;
  corpusWorkspace: string;
  sampleSize: number;
  /** Extractor identities required before a consumer reuses feature bounds. */
  extractors?: {
    commentDensity?: string;
  };
  features: {
    lineLengths: PerFeatureStats;
    identifierLengths: PerFeatureStats;
    commentDensity: PerFeatureStats;
    heaps: BasicStats;
    zipf: BasicStats;
  };
}

export interface PerFeatureStats extends BasicStats {
  /** Down-sampled reference distribution (10k points) for KS test. */
  sample: number[];
}

export interface BasicStats {
  n: number;
  mean: number;
  std: number;
  p5: number;
  p50: number;
  p95: number;
}

const data = baselineData as unknown as CorpusBaselines;

/** Get the corpus-derived baselines, or `null` if the JSON is unavailable. */
export function getCorpusBaselines(): CorpusBaselines | null {
  if (!data || typeof data !== 'object' || !('features' in data)) {
    return null;
  }
  return data;
}
