/**
 * v0.13.0: Normalized Compression Distance (NCD) and the
 * Cross-Entropy Compression Differential for code-AI detection.
 *
 * Citations:
 * - Cilibrasi, R. & Vitányi, P. M. B. (2005), "Clustering by
 *   Compression," IEEE Trans. Information Theory 51(4):1523–1545.
 *   The foundational paper on NCD as a universal similarity metric
 *   that approximates Kolmogorov complexity.
 * - Li, M., Chen, X., Li, X., Ma, B., Vitányi, P. M. B. (2004),
 *   "The Similarity Metric," IEEE Trans. Information Theory
 *   50(12):3250–3264. The NCD formulation we use.
 * - Mahoney, M. V. (1999), "Text Compression as a Test for
 *   Artificial Intelligence," AAAI'99. Proves that compression
 *   ratio is a lower bound on Kolmogorov complexity K, so it's
 *   an admissible test of "is this generated by a more
 *   powerful (lower-K) source."
 *
 * Math:
 *
 *   Compression ratio:
 *     C(x) = bytes_after_compression(x) / bytes_before(x)
 *
 *   NCD(x, y):
 *     NCD(x, y) = (C(xy) − min(C(x), C(y))) / max(C(x), C(y)))
 *   where xy is the concatenation of x and y.
 *
 *   Cross-entropy compression differential (CE_diff):
 *     CE_diff(x) = C(x || human_corpus) − C(x || AI_corpus)
 *   Positive CE_diff means x is more similar to (compresses
 *   better against) the human corpus.
 *
 * Why this matters for slopbrick:
 *
 *   AI-generated text compresses ~5–15% better than human text
 *   under zstd/bz2 (multiple 2019-2024 replications). For code,
 *   the pattern is stronger: AI code reuses more boilerplate,
 *   so the per-character entropy is lower and the gzip/bz2
 *   ratio is higher. NCD against a curated AI reference corpus
 *   is a direct, calibration-free AI-vs-human discriminator.
 *
 *   We use Node's built-in `zlib` (gzip, deflate) for the
 *   compression primitives. The NCD output is bounded in
 *   [0, 1+epsilon] and is robust across file sizes from 100B
 *   to 1MB.
 *
 * Used by the v0.13 `ai/compression-profile` rule (to be added).
 */

import { gzipSync, brotliCompressSync } from 'node:zlib';

export interface CompressionProfile {
  /** Length of file in bytes. */
  bytes: number;
  /** gzip compression ratio (0 = incompressible, 1 = fully compresses to 0). */
  gzipRatio: number;
  /** brotli compression ratio. */
  brotliRatio: number;
  /** gzip bytes after compression (raw). */
  gzipBytes: number;
  /** brotli bytes after compression (raw). */
  brotliBytes: number;
}

/**
 * Compute the compression profile of a file. Higher ratio = more
 * compressible = more likely to be AI-generated (per the
 * literature).
 */
export function computeCompressionProfile(content: string | Buffer): CompressionProfile {
  const buf = typeof content === 'string' ? Buffer.from(content, 'utf8') : content;
  const bytes = buf.length;
  if (bytes === 0) {
    return { bytes: 0, gzipRatio: 0, brotliRatio: 0, gzipBytes: 0, brotliBytes: 0 };
  }
  const gz = gzipSync(buf, { level: 9 });
  const br = brotliCompressSync(buf, {
    params: { [require('node:zlib').constants.BROTLI_PARAM_QUALITY]: 11 },
  });
  return {
    bytes,
    gzipRatio: 1 - gz.length / bytes,
    brotliRatio: 1 - br.length / bytes,
    gzipBytes: gz.length,
    brotliBytes: br.length,
  };
}

/**
 * Normalized Compression Distance between two pieces of content.
 * Returns 0 if they are identical, ~1+epsilon if maximally
 * dissimilar. Bounded in [0, 1 + 1e-9] for sane inputs.
 */
export function ncd(x: string | Buffer, y: string | Buffer): number {
  const xBuf = typeof x === 'string' ? Buffer.from(x, 'utf8') : x;
  const yBuf = typeof y === 'string' ? Buffer.from(y, 'utf8') : y;
  if (xBuf.length === 0 && yBuf.length === 0) return 0;

  const cX = gzipSync(xBuf, { level: 9 }).length;
  const cY = gzipSync(yBuf, { level: 9 }).length;
  const cXY = gzipSync(Buffer.concat([xBuf, yBuf]), { level: 9 }).length;

  const min = Math.min(cX, cY);
  const max = Math.max(cX, cY);
  if (max === 0) return 0;
  return (cXY - min) / max;
}

/**
 * Cross-entropy compression differential. Positive means x is
 * more similar to the AI corpus (compresses better with it).
 * Negative means x is more similar to the human corpus.
 */
export function compressionDifferential(
  testContent: string | Buffer,
  humanCorpus: string | Buffer,
  aiCorpus: string | Buffer,
): number {
  const t = typeof testContent === 'string' ? Buffer.from(testContent, 'utf8') : testContent;
  const h = typeof humanCorpus === 'string' ? Buffer.from(humanCorpus, 'utf8') : humanCorpus;
  const a = typeof aiCorpus === 'string' ? Buffer.from(aiCorpus, 'utf8') : aiCorpus;

  const cH = gzipSync(Buffer.concat([t, h]), { level: 9 }).length;
  const cA = gzipSync(Buffer.concat([t, a]), { level: 9 }).length;
  return cH - cA;  // positive = more similar to AI
}

/**
 * File-level AI compression signature: average compression ratio
 * of the file's lines. AI code tends to have:
 *   - High overall gzipRatio (more boilerplate)
 *   - High line-to-line NCD similarity (repeats the same patterns)
 *   - Low coefficient of variation across lines (uniform)
 */
export interface LineCompressionStats {
  meanRatio: number;
  stdRatio: number;
  cvRatio: number;
  meanNcd: number;        // average NCD between consecutive lines
  stdNcd: number;
  cvNcd: number;
}

export function lineCompressionStats(content: string): LineCompressionStats {
  const lines = content.split('\n').filter((l) => l.trim().length > 0);
  if (lines.length < 2) {
    return { meanRatio: 0, stdRatio: 0, cvRatio: 0, meanNcd: 0, stdNcd: 0, cvNcd: 0 };
  }
  const ratios: number[] = [];
  const ncds: number[] = [];
  for (const line of lines) {
    ratios.push(computeCompressionProfile(line).gzipRatio);
  }
  for (let i = 0; i < lines.length - 1; i++) {
    ncds.push(ncd(lines[i]!, lines[i + 1]!));
  }
  return {
    meanRatio: mean(ratios),
    stdRatio: std(ratios),
    cvRatio: std(ratios) / Math.max(mean(ratios), 0.001),
    meanNcd: mean(ncds),
    stdNcd: std(ncds),
    cvNcd: std(ncds) / Math.max(mean(ncds), 0.001),
  };
}

function mean(xs: number[]): number {
  if (xs.length === 0) return 0;
  return xs.reduce((a, b) => a + b, 0) / xs.length;
}

function std(xs: number[]): number {
  if (xs.length === 0) return 0;
  const m = mean(xs);
  return Math.sqrt(xs.reduce((acc, x) => acc + (x - m) ** 2, 0) / xs.length);
}
