import { mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { describe, expect, it } from 'vitest';

import { canonicalAuthorityRowsV2 } from '../../src/calibration/cal-002/authority';
import { builtinRules } from '../../src/rules/builtins';
import { RULE_HINTS } from '../../src/snippet/data';
import {
  assertQualityCopy,
  collectGeneratedCatalogCopy,
  collectPublicRuleCopy,
} from '../helpers/public-rule-copy';

const RULE_SOURCE_ROOT = join(__dirname, '..', '..', 'src', 'rules');
const GENERATED_CATALOG = join(__dirname, '..', '..', 'docs', 'rule-catalog.md');

function collectFailure(failures: string[], text: string, location: string): void {
  try {
    assertQualityCopy(text, location);
  } catch (error) {
    failures.push(error instanceof Error ? error.message : String(error));
  }
}

describe('CAL-002 quality authority public copy', () => {
  it.each([
    'An LLM added this fallback.',
    'LLMs default to this pattern.',
    'Machine-written output uses this fallback.',
    'Human-produced code uses this fallback.',
    'A language model produced this fallback.',
    'This is a model-created fallback.',
    'ChatGPT generated this fallback.',
    'GPT-4 wrote this branch.',
    'Amazon Q generated this fallback.',
    'GitLab Duo generated this branch.',
    'JetBrains Junie wrote this fallback.',
    'Google Bard authored this code.',
    'Roo Code produced this implementation.',
    'Kiro wrote this fallback.',
    'Jules generated this branch.',
    'Perplexity produced this implementation.',
    'Acme Forge generated this branch.',
    'Acme Forge produced fallback code.',
    'This fallback was generated by Acme Forge.',
    'Acme Forge built this fallback.',
    'Built by Acme Forge.',
    'Acme Forge implemented fallback code.',
    'Fallback code came from Acme Forge.',
    'v0 generated fallback code.',
    'bolt.new produced fallback code.',
    'Acme Forge has generated fallback code.',
    'generated by the Acme Forge.',
    'Acme Forge is the author of this fallback.',
    'This implementation is courtesy of Acme Forge.',
    'Artificial intelligence generated this fallback.',
    'A.I. generated this fallback.',
    'Claude wrote this branch.',
    'Agent-generated code uses this pattern.',
    'A coding agent produced this branch.',
    'Bot-written code uses this fallback.',
    'This output was created by an agent.',
  ])('rejects provenance or authorship framing: %s', (text) => {
    expect(() => assertQualityCopy(text, 'regression fixture')).toThrow(/provenance|authorship/i);
  });

  it('resolves cooked, assembled, helper-returned, and shorthand public copy', () => {
    const root = mkdtempSync(join(tmpdir(), 'cal-002-quality-source-copy-'));
    const sourcePath = join(root, 'example.ts');
    try {
      writeFileSync(
        sourcePath,
        [
          "const PREFIX = '\\u0041' + 'I';",
          "function helper(): string { return PREFIX + ' generated this output'; }",
          'function emit(message: string) { return { message }; }',
          "export const exampleRule = { id: 'quality/example', description: 'Observable condition',",
          "  analyze() { return [emit(helper()), { advice: 'human-' + 'produced copy' }]; } };",
          '',
        ].join('\n'),
      );
      const copy = collectPublicRuleCopy('quality/example', root);
      const emitted = copy.map((entry) => entry.text).join('\n');
      expect(emitted).toContain('AI generated this output');
      expect(emitted).toContain('human-produced copy');
      expect(() => assertQualityCopy(emitted, sourcePath)).toThrow(/provenance|authorship/i);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it.each([
    {
      name: 'direct indirection',
      declarations: '',
      expression: 'externalMessage()',
    },
    {
      name: 'one unresolved conditional branch',
      declarations: '',
      expression: "condition ? 'Observable condition' : externalMessage()",
    },
    {
      name: 'one unresolved helper return',
      declarations: [
        'function copy(condition: boolean): string {',
        "  if (condition) return 'Observable condition';",
        '  return externalMessage();',
        '}',
      ].join('\n'),
      expression: 'copy(condition)',
    },
    {
      name: 'a shadowed helper binding',
      declarations: [
        "function copy(): string { return 'Safe outer copy'; }",
        'function shadowedCopy(): string {',
        '  const copy = externalMessage;',
        '  return copy();',
        '}',
      ].join('\n'),
      expression: 'shadowedCopy()',
    },
    {
      name: 'a shadowed forwarded property',
      declarations: [
        "const hit = { message: 'Safe outer copy' };",
        'function shadowedCopy(): string {',
        '  const hit = externalMessage();',
        '  return hit.message;',
        '}',
      ].join('\n'),
      expression: 'shadowedCopy()',
    },
    {
      name: 'a mutable binding with a later unresolved write',
      declarations: [
        "let message = 'Observable condition';",
        'message = externalMessage();',
      ].join('\n'),
      expression: 'message',
    },
    {
      name: 'a mutable binding overwritten by a for-of target',
      declarations: [
        "let message = 'Observable condition';",
        'for (message of [externalMessage()]) {}',
      ].join('\n'),
      expression: 'message',
    },
    {
      name: 'a destructured binding overwritten by a for-of target',
      declarations: [
        "let message = 'Observable condition';",
        'for ({ message } of [{ message: externalMessage() }]) {}',
      ].join('\n'),
      expression: 'message',
    },
    {
      name: 'a mutable binding overwritten by a for-in target',
      declarations: [
        "let message = 'Observable condition';",
        "for (message in { 'GPT-4 wrote this branch.': true }) {}",
      ].join('\n'),
      expression: 'message',
    },
    {
      name: 'a forwarded property with a later unresolved write',
      declarations: [
        "const hit = { message: 'Observable condition' };",
        'hit.message = externalMessage();',
      ].join('\n'),
      expression: 'hit.message',
    },
    {
      name: 'a forwarded property shadowed by a function parameter',
      declarations: [
        "const hit = { message: 'Safe outer copy' };",
        'function forwarded(hit: { message: string }): string {',
        '  return hit.message;',
        '}',
      ].join('\n'),
      expression: 'forwarded(externalMessage() as unknown as { message: string })',
    },
    {
      name: 'a forwarded property with an unresolved computed-key write',
      declarations: [
        "const hit = { message: 'Observable condition' };",
        "const key = 'message';",
        'hit[key] = externalMessage();',
      ].join('\n'),
      expression: 'hit.message',
    },
    {
      name: 'a forwarded helper shadowed before a for-of call',
      declarations: [
        "function scan(): Array<{ message: string }> { return [{ message: 'Safe outer copy' }]; }",
        'function forwarded(): string {',
        '  const scan = externalMessage as unknown as () => Array<{ message: string }>; ',
        '  for (const hit of scan()) return hit.message;',
        "  return 'Observable condition';",
        '}',
      ].join('\n'),
      expression: 'forwarded()',
    },
    {
      name: 'an unresolved destructuring write',
      declarations: [
        "let message = 'Safe outer copy';",
        '({ message } = externalMessage() as unknown as { message: string });',
      ].join('\n'),
      expression: 'message',
    },
    {
      name: 'a forwarded accumulator helper with one unresolved return path',
      declarations: [
        'function scan(condition: boolean): Array<{ message: string }> {',
        '  const hits: Array<{ message: string }> = [];',
        "  hits.push({ message: 'Observable condition' });",
        '  if (condition) return externalMessage() as unknown as Array<{ message: string }>;',
        '  return hits;',
        '}',
        'function forwarded(): string {',
        '  for (const hit of scan(condition)) return hit.message;',
        "  return 'Observable condition';",
        '}',
      ].join('\n'),
      expression: 'forwarded()',
    },
    {
      name: 'a forwarded accumulator object with an unresolved spread',
      declarations: [
        'function scan(): Array<{ message: string }> {',
        '  const hits: Array<{ message: string }> = [];',
        "  hits.push({ message: 'Observable condition', ...externalMessage() as unknown as { message: string } });",
        '  return hits;',
        '}',
        'function forwarded(): string {',
        '  for (const hit of scan()) return hit.message;',
        "  return 'Observable condition';",
        '}',
      ].join('\n'),
      expression: 'forwarded()',
    },
    {
      name: 'a forwarded accumulator assigned to an alias',
      declarations: [
        'function scan(): Array<{ message: string }> {',
        '  const hits: Array<{ message: string }> = [];',
        '  let alias: Array<{ message: string }>;',
        '  alias = hits;',
        '  alias.push(externalMessage() as unknown as { message: string });',
        "  hits.push({ message: 'Observable condition' });",
        '  return hits;',
        '}',
        'function forwarded(): string {',
        '  for (const hit of scan()) return hit.message;',
        "  return 'Observable condition';",
        '}',
      ].join('\n'),
      expression: 'forwarded()',
    },
    {
      name: 'a computed accumulator mutation method',
      declarations: [
        'function scan(): Array<{ message: string }> {',
        '  const hits: Array<{ message: string }> = [];',
        '  hits["unshift"](externalMessage() as unknown as { message: string });',
        "  hits.push({ message: 'Observable condition' });",
        '  return hits;',
        '}',
        'function forwarded(): string {',
        '  for (const hit of scan()) return hit.message;',
        "  return 'Observable condition';",
        '}',
      ].join('\n'),
      expression: 'forwarded()',
    },
    {
      name: 'a type-wrapped accumulator escape',
      declarations: [
        'function scan(): Array<{ message: string }> {',
        '  const hits: Array<{ message: string }> = [];',
        '  externalMessage(hits as Array<{ message: string }>);',
        "  hits.push({ message: 'Observable condition' });",
        '  return hits;',
        '}',
        'function forwarded(): string {',
        '  for (const hit of scan()) return hit.message;',
        "  return 'Observable condition';",
        '}',
      ].join('\n'),
      expression: 'forwarded()',
    },
    {
      name: 'a nested function that captures the forwarded accumulator',
      declarations: [
        'function scan(): Array<{ message: string }> {',
        '  const hits: Array<{ message: string }> = [];',
        '  function inject(): void {',
        '    hits["unshift"](externalMessage() as unknown as { message: string });',
        '  }',
        '  inject();',
        "  hits.push({ message: 'Observable condition' });",
        '  return hits;',
        '}',
        'function forwarded(): string {',
        '  for (const hit of scan()) return hit.message;',
        "  return 'Observable condition';",
        '}',
      ].join('\n'),
      expression: 'forwarded()',
    },
    {
      name: 'a rest parameter with provenance-bearing later arguments',
      declarations: [
        'function scan(...parts: string[]): Array<{ message: string }> {',
        '  const hits: Array<{ message: string }> = [];',
        '  hits.push({ message: `copy: ${parts}` });',
        '  return hits;',
        '}',
        'function forwarded(): string {',
        "  for (const hit of scan('Observable condition', 'AI generated this output')) return hit.message;",
        "  return 'Observable condition';",
        '}',
      ].join('\n'),
      expression: 'forwarded()',
    },
    {
      name: 'an omitted parameter with an unresolved default',
      declarations: [
        'function scan(copy: string = externalMessage()): Array<{ message: string }> {',
        '  const hits: Array<{ message: string }> = [];',
        '  hits.push({ message: `copy: ${copy}` });',
        '  return hits;',
        '}',
        'function forwarded(): string {',
        '  for (const hit of scan()) return hit.message;',
        "  return 'Observable condition';",
        '}',
      ].join('\n'),
      expression: 'forwarded()',
    },
  ])('fails closed for $name', ({ declarations, expression }) => {
    const root = mkdtempSync(join(tmpdir(), 'cal-002-quality-unresolved-copy-'));
    const sourcePath = join(root, 'example.ts');
    try {
      writeFileSync(
        sourcePath,
        [
          "import { externalMessage } from './external';",
          declarations,
          "export const exampleRule = { id: 'quality/example', description: 'Observable condition',",
          `  analyze() { return [{ message: ${expression} }]; } };`,
          '',
        ].join('\n'),
      );
      expect(() => collectPublicRuleCopy('quality/example', root)).toThrow(/cannot resolve public copy/i);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it('fails closed when a direct emitted object spread can overwrite public copy', () => {
    const root = mkdtempSync(join(tmpdir(), 'cal-002-quality-direct-spread-'));
    const sourcePath = join(root, 'example.ts');
    try {
      writeFileSync(
        sourcePath,
        [
          "import { externalMessage } from './external';",
          "export const exampleRule = { id: 'quality/example', description: 'Observable condition',",
          '  analyze() {',
          "    return [{ message: 'Observable condition', ...externalMessage() as unknown as { message: string } }];",
          '  }',
          '};',
          '',
        ].join('\n'),
      );
      expect(() => collectPublicRuleCopy('quality/example', root)).toThrow(/cannot resolve public copy/i);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it('fails closed when a spread-only object can introduce public copy', () => {
    const root = mkdtempSync(join(tmpdir(), 'cal-002-quality-spread-only-'));
    const sourcePath = join(root, 'example.ts');
    try {
      writeFileSync(
        sourcePath,
        [
          "import { externalIssue } from './external';",
          "export const exampleRule = { id: 'quality/example', description: 'Observable condition',",
          '  analyze() { return [{ ...externalIssue() }]; }',
          '};',
          '',
        ].join('\n'),
      );
      expect(() => collectPublicRuleCopy('quality/example', root)).toThrow(/cannot resolve (?:potential )?public copy/i);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it.each([
    '() => [{ ...externalIssue() }]',
    'function namedAnalysis() { return [{ ...externalIssue() }]; }',
  ])('fails closed for a property-assigned analyze hook: %s', (analyze) => {
    const root = mkdtempSync(join(tmpdir(), 'cal-002-quality-property-analyze-'));
    const sourcePath = join(root, 'example.ts');
    try {
      writeFileSync(
        sourcePath,
        [
          "import { externalIssue } from './external';",
          "export const exampleRule = { id: 'quality/example', description: 'Observable condition',",
          `  analyze: ${analyze},`,
          '};',
          '',
        ].join('\n'),
      );
      expect(() => collectPublicRuleCopy('quality/example', root)).toThrow(/cannot resolve (?:potential )?public copy/i);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it.each([
    {
      name: 'a direct imported issue',
      declarations: '',
      body: 'return [externalIssue()];',
    },
    {
      name: 'an imported issue stored in a local alias',
      declarations: '',
      body: 'const issue = externalIssue(); return [issue];',
    },
    {
      name: 'a local issue helper with an imported return',
      declarations: 'function emit() { return externalIssue(); }',
      body: 'return [emit()];',
    },
    {
      name: 'a direct imported issue array',
      declarations: '',
      body: 'return externalIssues();',
    },
    {
      name: 'an imported issue pushed into a typed accumulator',
      declarations: '',
      body: 'const issues: Issue[] = []; issues.push(externalIssue()); return issues;',
    },
    {
      name: 'an imported issue pushed through computed syntax',
      declarations: '',
      body: "const issues: Issue[] = []; issues['push'](externalIssue()); return issues;",
    },
    {
      name: 'an imported issue array spread into a typed accumulator',
      declarations: '',
      body: 'const issues: Issue[] = []; issues.push(...externalIssues()); return issues;',
    },
    {
      name: 'a typed accumulator passed to an imported mutator',
      declarations: '',
      body: 'const issues: Issue[] = []; externalPopulate(issues); return issues;',
    },
    {
      name: 'a filter callback that mutates an emitted issue',
      declarations: '',
      body: [
        "const issues: Issue[] = [{ message: 'Observable condition' }];",
        "return issues.filter((issue) => { issue.message = 'GPT-4 wrote this branch.'; return true; });",
      ].join(' '),
    },
    {
      name: 'an executable helper-returned issue object',
      declarations: [
        'function emit() {',
        "  return { message: 'Observable condition',",
        "    get trigger() { this.message = 'GPT-4 wrote this branch.'; return true; },",
        '  };',
        '}',
      ].join(' '),
      body: 'const issue = emit(); void issue.trigger; return [issue];',
    },
    {
      name: 'a callback parameter shadowing a safe outer function',
      declarations: [
        "function emit() { return { message: 'Observable condition' }; }",
        'function collect(emit) { return [1].map(emit); }',
      ].join(' '),
      body: 'return collect(externalEmit);',
    },
    {
      name: 'a nested write through a typed accumulator element',
      declarations: '',
      body: [
        "const issues: Issue[] = [{ message: 'Observable condition' }];",
        "issues[0]!.message = 'GPT-4 wrote this branch.';",
        'return issues;',
      ].join(' '),
    },
    {
      name: 'a nested write through a typed issue tuple',
      declarations: '',
      body: [
        "const issues: [Issue] = [{ message: 'Observable condition' }];",
        "issues[0].message = 'GPT-4 wrote this branch.';",
        'return issues;',
      ].join(' '),
    },
    {
      name: 'an inherited public-copy property through __proto__',
      declarations: '',
      body: "return [{ __proto__: issuePrototype, message: 'Observable condition' }];",
    },
    {
      name: 'an inherited public-copy property through a __proto__ write',
      declarations: '',
      body: [
        "const issue = { message: 'Observable condition' };",
        'issue.__proto__ = issuePrototype;',
        'return [issue];',
      ].join(' '),
    },
    {
      name: 'an inherited public-copy property through Object.setPrototypeOf',
      declarations: '',
      body: [
        "const issue = { message: 'Observable condition' };",
        'Object.setPrototypeOf(issue, issuePrototype);',
        'return [issue];',
      ].join(' '),
    },
    {
      name: 'opaque copy spread by a helper-returned issue',
      declarations: [
        "function emit(copy) { return { message: 'Observable condition', ...copy }; }",
      ].join(' '),
      body: 'return [emit(externalIssue())];',
    },
    {
      name: 'a spread-only helper-returned issue',
      declarations: [
        'function emit(copy: Issue) { return { ...copy }; }',
      ].join(' '),
      body: 'return [emit(externalIssue())];',
    },
    {
      name: 'a spread-only helper-returned untyped issue',
      declarations: [
        'function emit(copy) { return { ...copy }; }',
      ].join(' '),
      body: 'return [emit(externalIssue())];',
    },
    {
      name: 'a spread-only helper-returned aliased Issue',
      declarations: [
        'type Finding = Issue;',
        'function emit(copy: Finding): Finding { return { ...copy }; }',
      ].join(' '),
      body: 'return [emit(externalIssue())];',
    },
    {
      name: 'an Issue-valued helper parameter shadowing safe outer copy',
      declarations: [
        "const issue: Issue = { message: 'Observable condition' };",
        'function identity(issue: Issue): Issue { return issue; }',
      ].join(' '),
      body: 'return [identity(externalIssue())];',
    },
    {
      name: 'an Issue-valued callback parameter shadowing safe outer copy',
      declarations: [
        "const issue: Issue = { message: 'Observable condition' };",
      ].join(' '),
      body: 'return externalIssues().map((issue: Issue) => issue);',
    },
    {
      name: 'a typed Issue-array element mutated through for-of iteration',
      declarations: '',
      body: [
        "const issues: Issue[] = [{ message: 'Observable condition' }];",
        'for (const issue of issues) issue.message = externalMessage();',
        'return issues;',
      ].join(' '),
    },
    {
      name: 'an aliased typed Issue-array element mutated through for-of iteration',
      declarations: 'type Findings = Issue[];',
      body: [
        "const issues: Findings = [{ message: 'Observable condition' }];",
        'for (const issue of issues) issue.message = externalMessage();',
        'return issues;',
      ].join(' '),
    },
    {
      name: 'an aliased typed Issue array passed to an opaque mutator',
      declarations: 'type Findings = Issue[];',
      body: [
        "const issues: Findings = [{ message: 'Observable condition' }];",
        'externalPopulate(issues);',
        'return issues;',
      ].join(' '),
    },
    {
      name: 'a generically aliased typed Issue array passed to an opaque mutator',
      declarations: [
        'type List<T> = T[];',
        'type Findings = List<Issue>;',
      ].join(' '),
      body: [
        "const issues: Findings = [{ message: 'Observable condition' }];",
        'externalPopulate(issues);',
        'return issues;',
      ].join(' '),
    },
    {
      name: 'a conditionally aliased typed Issue array passed to an opaque mutator',
      declarations: 'type Findings<T> = T extends unknown ? T[] : never;',
      body: [
        "const issues: Findings<Issue> = [{ message: 'Observable condition' }];",
        'externalPopulate(issues);',
        'return issues;',
      ].join(' '),
    },
    {
      name: 'a Readonly-wrapped typed Issue array passed to an opaque mutator',
      declarations: 'type Findings = Readonly<Issue[]>;',
      body: [
        "const issues: Findings = [{ message: 'Observable condition' }];",
        'externalPopulate(issues as unknown as Issue[]);',
        'return issues;',
      ].join(' '),
    },
    {
      name: 'a mapped typed Issue array passed to an opaque mutator',
      declarations: [
        'type MutableShape<T> = { -readonly [K in keyof T]: T[K] };',
        'type Findings = MutableShape<Issue[]>;',
      ].join(' '),
      body: [
        "const issues: Findings = [{ message: 'Observable condition' }];",
        'externalPopulate(issues as unknown as Issue[]);',
        'return issues;',
      ].join(' '),
    },
    {
      name: 'a typed Issue-array element mutated through a callback',
      declarations: '',
      body: [
        "const issues: Issue[] = [{ message: 'Observable condition' }];",
        'issues.map((issue) => { issue.message = externalMessage(); return issue; });',
        'return issues;',
      ].join(' '),
    },
    {
      name: 'a typed Issue array mutated through a container property',
      declarations: '',
      body: [
        "const issues: Issue[] = [{ message: 'Observable condition' }];",
        'const box = { issues };',
        'box.issues.push(externalIssue());',
        'return issues;',
      ].join(' '),
    },
    {
      name: 'a typed Issue array spread into an opaque call',
      declarations: '',
      body: [
        "const issues: Issue[] = [{ message: 'Observable condition' }];",
        'externalPopulate([...issues]);',
        'return issues;',
      ].join(' '),
    },
    {
      name: 'a typed Issue array passed to an opaque constructor',
      declarations: '',
      body: [
        "const issues: Issue[] = [{ message: 'Observable condition' }];",
        'new ExternalMutator(issues);',
        'return issues;',
      ].join(' '),
    },
    {
      name: 'a typed Issue array exposed through an accessor container',
      declarations: '',
      body: [
        "const issues: Issue[] = [{ message: 'Observable condition' }];",
        'const box = { get current() { return issues; } };',
        'externalConsume(box);',
        'return issues;',
      ].join(' '),
    },
    {
      name: 'a typed Issue array exposed through nested concise closures',
      declarations: '',
      body: [
        "const issues: Issue[] = [{ message: 'Observable condition' }];",
        'externalConsume(() => () => issues);',
        'return issues;',
      ].join(' '),
    },
    {
      name: 'a typed Issue array exposed through an object-held concise closure',
      declarations: '',
      body: [
        "const issues: Issue[] = [{ message: 'Observable condition' }];",
        'const box = { current: () => issues };',
        'box.current().push(externalIssue());',
        'return issues;',
      ].join(' '),
    },
    {
      name: 'a typed Issue array exposed through a tagged template',
      declarations: '',
      body: [
        "const issues: Issue[] = [{ message: 'Observable condition' }];",
        'externalTag`${issues}`;',
        'return issues;',
      ].join(' '),
    },
    {
      name: 'a typed Issue array exposed through throw and catch',
      declarations: '',
      body: [
        "const issues: Issue[] = [{ message: 'Observable condition' }];",
        'try { throw issues; } catch (value) { externalPopulate(value as Issue[]); }',
        'return issues;',
      ].join(' '),
    },
    {
      name: 'a typed Issue array exposed through a generator yield',
      declarations: '',
      body: [
        "const issues: Issue[] = [{ message: 'Observable condition' }];",
        'function* expose() { yield issues; }',
        'externalConsume(expose());',
        'return issues;',
      ].join(' '),
    },
    {
      name: 'inherited copy injected through Object.prototype',
      declarations: '',
      body: [
        '(Object.prototype as { advice?: string }).advice = externalMessage();',
        "return [{ message: 'Observable condition' }];",
      ].join(' '),
    },
    {
      name: 'inherited copy injected through a computed prototype receiver',
      declarations: '',
      body: [
        "(Reflect.getPrototypeOf({}) as { advice?: string }).advice = externalMessage();",
        "return [{ message: 'Observable condition' }];",
      ].join(' '),
    },
    {
      name: 'inherited copy injected through Reflect.set',
      declarations: '',
      body: [
        "Reflect.set(Reflect.getPrototypeOf({}), 'advice', externalMessage());",
        "return [{ message: 'Observable condition' }];",
      ].join(' '),
    },
    {
      name: 'inherited copy injected through a dynamic Reflect.set key',
      declarations: '',
      body: [
        "const key = 'advice';",
        'Reflect.set(Reflect.getPrototypeOf({}), key, externalMessage());',
        "return [{ message: 'Observable condition' }];",
      ].join(' '),
    },
    {
      name: 'inherited copy injected through a computed prototype and dynamic key',
      declarations: '',
      body: [
        "const key = 'advice';",
        "Reflect.set(Object['prototype'], key, externalMessage());",
        "return [{ message: 'Observable condition' }];",
      ].join(' '),
    },
    {
      name: 'inherited copy injected through __proto__ and a dynamic key',
      declarations: '',
      body: [
        "const key = 'advice';",
        '({} as any).__proto__[key] = externalMessage();',
        "return [{ message: 'Observable condition' }];",
      ].join(' '),
    },
    {
      name: 'inherited copy injected through a computed __proto__ key',
      declarations: '',
      body: [
        "const key = '__proto__';",
        'Object.assign(({} as any)[key], externalIssue());',
        "return [{ message: 'Observable condition' }];",
      ].join(' '),
    },
    {
      name: 'inherited copy injected through constructor.prototype',
      declarations: '',
      body: [
        'Object.assign(({}).constructor.prototype, externalIssue());',
        "return [{ message: 'Observable condition' }];",
      ].join(' '),
    },
    {
      name: 'inherited copy injected through a destructured getPrototypeOf alias',
      declarations: '',
      body: [
        'const { getPrototypeOf } = Reflect;',
        'Object.assign(getPrototypeOf({}), externalIssue());',
        "return [{ message: 'Observable condition' }];",
      ].join(' '),
    },
    {
      name: 'inherited copy injected through Object.assign',
      declarations: '',
      body: [
        'Object.assign(Reflect.getPrototypeOf({}), externalIssue());',
        "return [{ message: 'Observable condition' }];",
      ].join(' '),
    },
    {
      name: 'an inherited typed-array transform override',
      declarations: '',
      body: [
        "const issues: Issue[] = [{ message: 'Observable condition' }];",
        '(Array.prototype as { slice: typeof externalIssues }).slice = externalIssues;',
        'return issues.slice();',
      ].join(' '),
    },
    {
      name: 'an inherited typed-array transform override through __proto__',
      declarations: '',
      body: [
        "const issues: Issue[] = [{ message: 'Observable condition' }];",
        '([] as any).__proto__.slice = externalIssues;',
        'return issues.slice();',
      ].join(' '),
    },
    {
      name: 'an overridden typed-accumulator slice method',
      declarations: '',
      body: [
        "const issues: Issue[] = [{ message: 'Observable condition' }];",
        'issues.slice = externalIssues;',
        'return issues.slice();',
      ].join(' '),
    },
    {
      name: 'direct eval that can rewrite emitted public copy',
      declarations: '',
      body: [
        "const issues: Issue[] = [{ message: 'Observable condition' }];",
        `eval('issues[0].message = "GPT-4 wrote this branch."');`,
        'return issues;',
      ].join(' '),
    },
    {
      name: 'destructured eval alias that can rewrite inherited public copy',
      declarations: '',
      body: [
        'const { eval: run } = globalThis;',
        `run('Object.prototype.advice = "GPT-4 wrote this branch."');`,
        "return [{ message: 'Observable condition' }];",
      ].join(' '),
    },
    {
      name: 'computed eval key that can rewrite inherited public copy',
      declarations: '',
      body: [
        "const key = 'ev' + 'al';",
        `(globalThis as any)[key]('Object.prototype.advice = "GPT-4 wrote this branch."');`,
        "return [{ message: 'Observable condition' }];",
      ].join(' '),
    },
    {
      name: 'dynamic Function construction that can rewrite inherited public copy',
      declarations: '',
      body: [
        `Function('Object.prototype.advice = "GPT-4 wrote this branch."')();`,
        "return [{ message: 'Observable condition' }];",
      ].join(' '),
    },
  ])('fails closed for opaque analyze emission from $name', ({ declarations, body }) => {
    const root = mkdtempSync(join(tmpdir(), 'cal-002-quality-opaque-emission-'));
    const sourcePath = join(root, 'example.ts');
    try {
      writeFileSync(
        join(root, 'external.ts'),
        [
          "export function externalIssue() { return { message: 'GPT-4 wrote this branch.' }; }",
          "export function externalIssues() { return [{ message: 'Amazon Q generated this fallback.' }]; }",
          "export function externalPopulate(issues: Array<{ message: string }>) { issues.push(externalIssue()); }",
          "export function externalEmit() { return { message: 'GPT-4 wrote this branch.' }; }",
          "export function externalMessage() { return 'GPT-4 wrote this branch.'; }",
          'export function externalConsume(_value: unknown) {}',
          'export function externalTag(_strings: TemplateStringsArray, ..._values: unknown[]) {}',
          'export class ExternalMutator { constructor(issues: Array<{ message: string }>) { issues[0]!.message = externalMessage(); } }',
          "export const issuePrototype = { advice: 'GPT-4 wrote this branch.' };",
          '',
        ].join('\n'),
      );
      writeFileSync(
        sourcePath,
        [
          "import { ExternalMutator, externalConsume, externalEmit, externalIssue, externalIssues, externalMessage, externalPopulate, externalTag, issuePrototype } from './external';",
          declarations,
          "export const exampleRule = { id: 'quality/example', description: 'Observable condition',",
          `  analyze() { ${body} }`,
          '};',
          '',
        ].join('\n'),
      );
      expect(() => collectPublicRuleCopy('quality/example', root)).toThrow(/cannot resolve public copy/i);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it('allows a rule create hook to forward context without treating it as emitted issue copy', () => {
    const root = mkdtempSync(join(tmpdir(), 'cal-002-quality-create-context-'));
    const sourcePath = join(root, 'example.ts');
    try {
      writeFileSync(
        sourcePath,
        [
          "export const exampleRule = { id: 'quality/example', description: 'Observable condition',",
          '  create(context: object) { return { ...context, enabled: true }; },',
          "  analyze() { return [{ message: 'Observable condition' }]; }",
          '};',
          '',
        ].join('\n'),
      );
      expect(collectPublicRuleCopy('quality/example', root)).toEqual(expect.arrayContaining([
        expect.objectContaining({ property: 'description', text: 'Observable condition' }),
        expect.objectContaining({ property: 'message', text: 'Observable condition' }),
      ]));
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it('allows a non-Issue helper accumulator to spread its own structural records', () => {
    const root = mkdtempSync(join(tmpdir(), 'cal-002-quality-non-issue-spread-'));
    const sourcePath = join(root, 'example.ts');
    try {
      writeFileSync(
        sourcePath,
        [
          'interface Region { start: number; end: number }',
          'function collect(region: Region): Region[] {',
          '  const regions: Region[] = [];',
          '  regions.push({ ...region, end: region.end + 1 });',
          '  return regions;',
          '}',
          "export const exampleRule = { id: 'quality/example', description: 'Observable condition',",
          "  analyze() { collect({ start: 0, end: 1 }); return [{ message: 'Observable condition' }]; }",
          '};',
          '',
        ].join('\n'),
      );
      expect(collectPublicRuleCopy('quality/example', root)).toEqual(expect.arrayContaining([
        expect.objectContaining({ property: 'description', text: 'Observable condition' }),
        expect.objectContaining({ property: 'message', text: 'Observable condition' }),
      ]));
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it('fails closed for getter-only public copy', () => {
    const root = mkdtempSync(join(tmpdir(), 'cal-002-quality-getter-copy-'));
    const sourcePath = join(root, 'example.ts');
    try {
      writeFileSync(
        sourcePath,
        [
          "export const exampleRule = { id: 'quality/example', description: 'Observable condition',",
          '  analyze() {',
          "    return [{ get message() { return 'AI generated this output'; } }];",
          '  }',
          '};',
          '',
        ].join('\n'),
      );
      expect(() => collectPublicRuleCopy('quality/example', root)).toThrow(/cannot resolve public copy/i);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it('fails closed when an empty default resolution reaches a conditional public-copy branch', () => {
    const root = mkdtempSync(join(tmpdir(), 'cal-002-quality-empty-branch-'));
    const sourcePath = join(root, 'example.ts');
    try {
      writeFileSync(
        sourcePath,
        [
          "import { externalMessage } from './external';",
          'function emit(copy: string = externalMessage()) {',
          "  return { message: condition ? copy : 'Observable condition' };",
          '}',
          "export const exampleRule = { id: 'quality/example', description: 'Observable condition',",
          '  analyze() { return [emit()]; }',
          '};',
          '',
        ].join('\n'),
      );
      expect(() => collectPublicRuleCopy('quality/example', root)).toThrow(/cannot resolve public copy/i);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it('preserves a known-empty local initializer instead of converting it to a runtime placeholder', () => {
    const root = mkdtempSync(join(tmpdir(), 'cal-002-quality-empty-local-'));
    const sourcePath = join(root, 'example.ts');
    try {
      writeFileSync(
        sourcePath,
        [
          "import { externalMessage } from './external';",
          'function source(copy: string = externalMessage()): string { return copy; }',
          "export const exampleRule = { id: 'quality/example', description: 'Observable condition',",
          '  analyze() {',
          '    const local = source();',
          '    return [{ message: `copy: ${local}` }];',
          '  }',
          '};',
          '',
        ].join('\n'),
      );
      expect(() => collectPublicRuleCopy('quality/example', root)).toThrow(/cannot resolve public copy/i);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it('fails closed for an unresolved imported call stored in a local interpolation', () => {
    const root = mkdtempSync(join(tmpdir(), 'cal-002-quality-unresolved-local-'));
    const sourcePath = join(root, 'example.ts');
    try {
      writeFileSync(
        sourcePath,
        [
          "import { externalMessage } from './external';",
          "export const exampleRule = { id: 'quality/example', description: 'Observable condition',",
          '  analyze() {',
          '    const local = externalMessage();',
          '    return [{ message: `copy: ${local}` }];',
          '  }',
          '};',
          '',
        ].join('\n'),
      );
      expect(() => collectPublicRuleCopy('quality/example', root)).toThrow(/cannot resolve public copy/i);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it('fails closed for a destructured local that shadows safe outer copy', () => {
    const root = mkdtempSync(join(tmpdir(), 'cal-002-quality-destructured-shadow-'));
    const sourcePath = join(root, 'example.ts');
    try {
      writeFileSync(
        sourcePath,
        [
          "import { externalMessage } from './external';",
          "export const exampleRule = { id: 'quality/example', description: 'Observable condition',",
          '  analyze() {',
          "    const message = 'Observable condition';",
          '    {',
          '      const { message } = externalMessage() as { message: string };',
          '      return [{ message }];',
          '    }',
          '  }',
          '};',
          '',
        ].join('\n'),
      );
      expect(() => collectPublicRuleCopy('quality/example', root)).toThrow(/cannot resolve public copy/i);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it('fails closed when an unresolved computed key could emit public copy', () => {
    const root = mkdtempSync(join(tmpdir(), 'cal-002-quality-computed-key-'));
    const sourcePath = join(root, 'example.ts');
    try {
      writeFileSync(
        sourcePath,
        [
          "const key = 'message';",
          "export const exampleRule = { id: 'quality/example', description: 'Observable condition',",
          "  analyze() { return [{ [key]: 'AI generated this output' }]; }",
          '};',
          '',
        ].join('\n'),
      );
      expect(() => collectPublicRuleCopy('quality/example', root)).toThrow(/cannot resolve (?:potential )?public copy/i);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it('fails closed for a destructured for-of binding that shadows safe outer copy', () => {
    const root = mkdtempSync(join(tmpdir(), 'cal-002-quality-for-of-shadow-'));
    const sourcePath = join(root, 'example.ts');
    try {
      writeFileSync(
        sourcePath,
        [
          "import { externalMessages } from './external';",
          "export const exampleRule = { id: 'quality/example', description: 'Observable condition',",
          '  analyze() {',
          "    const message = 'Observable condition';",
          '    for (const { message } of externalMessages() as Array<{ message: string }>) {',
          '      return [{ message }];',
          '    }',
          '    return [];',
          '  }',
          '};',
          '',
        ].join('\n'),
      );
      expect(() => collectPublicRuleCopy('quality/example', root)).toThrow(/cannot resolve public copy/i);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it.each([
    "['AI generated this output']",
    'copies',
    'collectCopies()',
  ])('resolves statically visible for-of iterable copy from %s', (iterable) => {
    const root = mkdtempSync(join(tmpdir(), 'cal-002-quality-static-for-of-'));
    const sourcePath = join(root, 'example.ts');
    try {
      writeFileSync(
        sourcePath,
        [
          "const copies = ['AI generated this output'] as const;",
          "function collectCopies() { return ['AI generated this output'] as const; }",
          "export const exampleRule = { id: 'quality/example', description: 'Observable condition',",
          '  analyze() {',
          `    for (const copy of ${iterable}) return [{ message: \`copy: \${copy}\` }];`,
          '    return [];',
          '  }',
          '};',
          '',
        ].join('\n'),
      );
      const emitted = collectPublicRuleCopy('quality/example', root)
        .map((entry) => entry.text)
        .join('\n');
      expect(emitted).toContain('copy: AI generated this output');
      expect(() => assertQualityCopy(emitted, sourcePath)).toThrow(/provenance|authorship/i);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it.each([
    "identity(['AI generated this output'])",
    'identity()',
    "identity(flag ? ['Observable condition'] : ['AI generated this output'])",
  ])('resolves static iterable copy through a local helper parameter: %s', (iterable) => {
    const root = mkdtempSync(join(tmpdir(), 'cal-002-quality-iterable-parameter-'));
    const sourcePath = join(root, 'example.ts');
    try {
      writeFileSync(
        sourcePath,
        [
          'const flag = true;',
          "function identity(values: readonly string[] = ['AI generated this output']) { return values; }",
          "export const exampleRule = { id: 'quality/example', description: 'Observable condition',",
          '  analyze() {',
          `    for (const copy of ${iterable}) return [{ message: \`copy: \${copy}\` }];`,
          '    return [];',
          '  }',
          '};',
          '',
        ].join('\n'),
      );
      const emitted = collectPublicRuleCopy('quality/example', root)
        .map((entry) => entry.text)
        .join('\n');
      expect(emitted).toContain('copy: AI generated this output');
      expect(() => assertQualityCopy(emitted, sourcePath)).toThrow(/provenance|authorship/i);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it('fails closed when a returned iterable parameter escapes through a callback first', () => {
    const root = mkdtempSync(join(tmpdir(), 'cal-002-quality-iterable-parameter-escape-'));
    const sourcePath = join(root, 'example.ts');
    try {
      writeFileSync(
        sourcePath,
        [
          "function append(target: string[]) { target.unshift('AI generated this output'); }",
          'function identity(values: string[]) { [values].forEach(append); return values; }',
          "export const exampleRule = { id: 'quality/example', description: 'Observable condition',",
          '  analyze() {',
          "    for (const copy of identity(['Observable condition'])) {",
          '      return [{ message: `copy: ${copy}` }];',
          '    }',
          '    return [];',
          '  }',
          '};',
          '',
        ].join('\n'),
      );
      expect(() => collectPublicRuleCopy('quality/example', root)).toThrow(/cannot resolve public copy/i);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it.each([
    "function expose() { return values; } mutate(expose()); return values;",
    "const holder = { get current() { return values; } }; mutate(holder.current); return values;",
  ])('fails closed when a returned iterable parameter escapes through a nested return: %s', (body) => {
    const root = mkdtempSync(join(tmpdir(), 'cal-002-quality-iterable-nested-return-'));
    const sourcePath = join(root, 'example.ts');
    try {
      writeFileSync(
        sourcePath,
        [
          "function mutate(target: string[]) { target.unshift('AI generated this output'); }",
          `function identity(values: string[]) { ${body} }`,
          "export const exampleRule = { id: 'quality/example', description: 'Observable condition',",
          '  analyze() {',
          "    for (const copy of identity(['Observable condition'])) {",
          '      return [{ message: `copy: ${copy}` }];',
          '    }',
          '    return [];',
          '  }',
          '};',
          '',
        ].join('\n'),
      );
      expect(() => collectPublicRuleCopy('quality/example', root)).toThrow(/cannot resolve public copy/i);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it.each([
    "arguments[0].unshift('AI generated this output'); return values;",
    "(() => arguments[0].unshift('AI generated this output'))(); return values;",
  ])('fails closed when a returned iterable parameter escapes through arguments: %s', (body) => {
    const root = mkdtempSync(join(tmpdir(), 'cal-002-quality-iterable-arguments-'));
    const sourcePath = join(root, 'example.ts');
    try {
      writeFileSync(
        sourcePath,
        [
          `function identity(values: string[]) { ${body} }`,
          "export const exampleRule = { id: 'quality/example', description: 'Observable condition',",
          '  analyze() {',
          "    for (const copy of identity(['Observable condition'])) {",
          '      return [{ message: `copy: ${copy}` }];',
          '    }',
          '    return [];',
          '  }',
          '};',
          '',
        ].join('\n'),
      );
      expect(() => collectPublicRuleCopy('quality/example', root)).toThrow(/cannot resolve public copy/i);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it.each([
    "copies.push('AI generated this output');",
    "copies['push']('AI generated this output');",
    "copies[\"unshift\"]('AI generated this output');",
    "const alias = copies; alias.push('AI generated this output');",
    "const alias = copies as string[]; alias['unshift']('AI generated this output');",
    "let alias: string[]; alias = copies; alias.push('AI generated this output');",
    "const method = 'push'; copies[method]('AI generated this output');",
    "function append(values: string[]) { values.push('AI generated this output'); } append(copies);",
    "function inner(values: string[]) { values.unshift('AI generated this output'); } function outer(values: string[]) { inner(values); } outer(copies);",
    "function append(values: string[] = copies) { values.unshift('AI generated this output'); } append();",
    "function append(values: string[] = copies) { values.unshift('AI generated this output'); } append(undefined);",
    "function append(values: string[]): void; function append(values: string[]) { values.unshift('AI generated this output'); } append(copies);",
    "const flag = true; function append(values: string[]) { values.unshift('AI generated this output'); } append(flag ? copies : []);",
    "function append(...groups: string[][]) { groups[0]!.unshift('AI generated this output'); } append(copies);",
    "function append([values]: [string[]]) { values.unshift('AI generated this output'); } append([copies]);",
    "function append(values: string[]) { values.unshift('AI generated this output'); } [copies].forEach(append);",
    "copies[0] = 'AI generated this output';",
    "copies = ['AI generated this output'];",
  ])('fails closed when a static iterable alias is mutated: %s', (mutation) => {
    const root = mkdtempSync(join(tmpdir(), 'cal-002-quality-mutated-iterable-'));
    const sourcePath = join(root, 'example.ts');
    try {
      writeFileSync(
        sourcePath,
        [
          "let copies = ['Observable condition'];",
          "export const exampleRule = { id: 'quality/example', description: 'Observable condition',",
          '  analyze() {',
          `    ${mutation}`,
          '    for (const copy of copies) return [{ message: `copy: ${copy}` }];',
          '    return [];',
          '  }',
          '};',
          '',
        ].join('\n'),
      );
      expect(() => collectPublicRuleCopy('quality/example', root)).toThrow(/cannot resolve public copy/i);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it.each([
    'export { copies };',
    'export { copies as exposedCopies };',
  ])('fails closed when a static iterable binding escapes through an export: %s', (exportLine) => {
    const root = mkdtempSync(join(tmpdir(), 'cal-002-quality-exported-iterable-'));
    const sourcePath = join(root, 'example.ts');
    try {
      writeFileSync(
        sourcePath,
        [
          "const copies = ['Observable condition'];",
          exportLine,
          "export const exampleRule = { id: 'quality/example', description: 'Observable condition',",
          '  analyze() {',
          '    for (const copy of copies) return [{ message: `copy: ${copy}` }];',
          '    return [];',
          '  }',
          '};',
          '',
        ].join('\n'),
      );
      expect(() => collectPublicRuleCopy('quality/example', root)).toThrow(/cannot resolve public copy/i);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it.each([
    "issue.message = 'AI generated this output';",
    "(issue as { message: string }).message = 'AI generated this output';",
    "(issue as Record<string, string>)['message'] = 'AI generated this output';",
    "const alias = issue; alias.message = 'AI generated this output';",
    "function overwrite(target: { message: string }) { target.message = 'AI generated this output'; } overwrite(issue);",
    "function overwrite(target = issue) { target.message = 'AI generated this output'; } overwrite();",
    "function overwrite(target = issue) { target.message = 'AI generated this output'; } overwrite(undefined);",
    "function overwrite(target: { message: string }): void; function overwrite(target: { message: string }) { target.message = 'AI generated this output'; } overwrite(issue);",
    "const flag = true; function overwrite(target: { message: string }) { target.message = 'AI generated this output'; } overwrite(flag ? issue : { message: 'Observable condition' });",
    "function overwrite([target]: [{ message: string }]) { target.message = 'AI generated this output'; } overwrite([issue]);",
    "function overwrite(target: { message: string }) { target.message = 'AI generated this output'; } [issue].forEach(overwrite);",
    "function expose() { return issue; } expose().message = 'AI generated this output';",
    "function expose() { const pending: Array<{ message: string }> = []; pending.push(issue); return pending; } expose()[0]!.message = 'AI generated this output';",
  ])('fails closed when a bound public-copy object is overwritten: %s', (mutation) => {
    const root = mkdtempSync(join(tmpdir(), 'cal-002-quality-object-overwrite-'));
    const sourcePath = join(root, 'example.ts');
    try {
      writeFileSync(
        sourcePath,
        [
          "const issue = { message: 'Observable condition' };",
          mutation,
          "export const exampleRule = { id: 'quality/example', description: 'Observable condition',",
          '  analyze() { return [issue]; }',
          '};',
          '',
        ].join('\n'),
      );
      expect(() => collectPublicRuleCopy('quality/example', root)).toThrow(/cannot resolve public copy/i);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it('fails closed when bound public copy is passed to an unresolved imported helper', () => {
    const root = mkdtempSync(join(tmpdir(), 'cal-002-quality-external-object-escape-'));
    const sourcePath = join(root, 'example.ts');
    try {
      writeFileSync(
        join(root, 'external.ts'),
        "export function overwrite(target: { message: string }) { target.message = 'AI generated this output'; }\n",
      );
      writeFileSync(
        sourcePath,
        [
          "import { overwrite } from './external';",
          "const issue = { message: 'Observable condition' };",
          'overwrite(issue);',
          "export const exampleRule = { id: 'quality/example', description: 'Observable condition',",
          '  analyze() { return [issue]; }',
          '};',
          '',
        ].join('\n'),
      );
      expect(() => collectPublicRuleCopy('quality/example', root)).toThrow(/cannot resolve public copy/i);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it('fails closed when a typed issue accumulator mutates an emitted object by index', () => {
    const root = mkdtempSync(join(tmpdir(), 'cal-002-quality-accumulator-mutation-'));
    const sourcePath = join(root, 'example.ts');
    try {
      writeFileSync(
        sourcePath,
        [
          "export const exampleRule = { id: 'quality/example', description: 'Observable condition',",
          '  analyze() {',
          "    const issue = { message: 'Observable condition' };",
          '    const pending: Issue[] = [];',
          '    pending.push(issue);',
          "    pending[0]!.message = 'AI generated this output';",
          '    return pending;',
          '  }',
          '};',
          '',
        ].join('\n'),
      );
      expect(() => collectPublicRuleCopy('quality/example', root)).toThrow(/cannot resolve public copy/i);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it('resolves a static local object property used in emitted copy', () => {
    const root = mkdtempSync(join(tmpdir(), 'cal-002-quality-static-property-'));
    const sourcePath = join(root, 'example.ts');
    try {
      writeFileSync(
        sourcePath,
        [
          "const copy = { value: 'AI generated this output' };",
          "export const exampleRule = { id: 'quality/example', description: 'Observable condition',",
          '  analyze() { return [{ message: `copy: ${copy.value}` }]; }',
          '};',
          '',
        ].join('\n'),
      );
      const emitted = collectPublicRuleCopy('quality/example', root)
        .map((entry) => entry.text)
        .join('\n');
      expect(emitted).toContain('copy: AI generated this output');
      expect(() => assertQualityCopy(emitted, sourcePath)).toThrow(/provenance|authorship/i);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it('allows checker-proven non-text properties from a runtime helper result', () => {
    const root = mkdtempSync(join(tmpdir(), 'cal-002-quality-runtime-number-'));
    const sourcePath = join(root, 'example.ts');
    try {
      writeFileSync(
        join(root, 'external.ts'),
        'export function externalMetrics(): { readonly total: number } { return { total: 1 }; }\n',
      );
      for (let index = 0; index < 7; index += 1) {
        writeFileSync(join(root, `support-${index}.ts`), `export const support${index} = ${index};\n`);
      }
      writeFileSync(
        sourcePath,
        [
          "import { externalMetrics } from './external';",
          'const metrics = externalMetrics();',
          "export const exampleRule = { id: 'quality/example', description: 'Observable condition',",
          '  analyze() { return [{ message: `total: ${metrics.total}` }]; }',
          '};',
          '',
        ].join('\n'),
      );
      expect(collectPublicRuleCopy('quality/example', root).map((entry) => entry.text))
        .toContain('total: {runtime value}');
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it('fails closed when an any-returning call is annotated as non-text', () => {
    const root = mkdtempSync(join(tmpdir(), 'cal-002-quality-runtime-any-'));
    const sourcePath = join(root, 'example.ts');
    try {
      writeFileSync(
        join(root, 'external.ts'),
        "export function externalCopy(): any { return { value: 'GPT-4 wrote this branch.' }; }\n",
      );
      for (let index = 0; index < 7; index += 1) {
        writeFileSync(join(root, `support-${index}.ts`), `export const support${index} = ${index};\n`);
      }
      writeFileSync(
        sourcePath,
        [
          "import { externalCopy } from './external';",
          'const copy: { readonly value: number } = externalCopy();',
          "export const exampleRule = { id: 'quality/example', description: 'Observable condition',",
          '  analyze() { return [{ message: `copy: ${copy.value}` }]; }',
          '};',
          '',
        ].join('\n'),
      );
      expect(() => collectPublicRuleCopy('quality/example', root)).toThrow(/cannot resolve public copy/i);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it('fails closed for an explicitly text-bearing imported-call property', () => {
    const root = mkdtempSync(join(tmpdir(), 'cal-002-quality-runtime-text-'));
    const sourcePath = join(root, 'example.ts');
    try {
      writeFileSync(
        sourcePath,
        [
          "import { externalCopy } from './external';",
          'const copy: { readonly value: string } = externalCopy();',
          "export const exampleRule = { id: 'quality/example', description: 'Observable condition',",
          '  analyze() { return [{ message: `copy: ${copy.value}` }]; }',
          '};',
          '',
        ].join('\n'),
      );
      expect(() => collectPublicRuleCopy('quality/example', root)).toThrow(/cannot resolve public copy/i);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it.each([
    [
      "get trigger() { this.message = 'AI generated this output'; return true; }",
      'void issue.trigger;',
    ],
    [
      "set trigger(value: boolean) { if (value) this.message = 'AI generated this output'; }",
      'issue.trigger = true;',
    ],
  ])('fails closed when a non-public accessor can rewrite emitted copy', (member, access) => {
    const root = mkdtempSync(join(tmpdir(), 'cal-002-quality-accessor-mutation-'));
    const sourcePath = join(root, 'example.ts');
    try {
      writeFileSync(
        sourcePath,
        [
          "const issue = { message: 'Observable condition',",
          `  ${member}`,
          '};',
          access,
          "export const exampleRule = { id: 'quality/example', description: 'Observable condition',",
          '  analyze() { return [issue]; }',
          '};',
          '',
        ].join('\n'),
      );
      expect(() => collectPublicRuleCopy('quality/example', root)).toThrow(/cannot resolve public copy/i);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it('allows a bound public-copy object to receive a non-copy field after construction', () => {
    const root = mkdtempSync(join(tmpdir(), 'cal-002-quality-object-non-copy-write-'));
    const sourcePath = join(root, 'example.ts');
    try {
      writeFileSync(
        sourcePath,
        [
          "const issue = { message: 'Observable condition', fix: undefined as object | undefined };",
          'issue.fix = { kind: \'safe-fix\' };',
          "export const exampleRule = { id: 'quality/example', description: 'Observable condition',",
          '  analyze() { return [issue]; }',
          '};',
          '',
        ].join('\n'),
      );
      expect(collectPublicRuleCopy('quality/example', root)).toEqual(expect.arrayContaining([
        expect.objectContaining({ property: 'message', text: 'Observable condition' }),
      ]));
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it('resolves a shadowed undefined argument instead of assuming the global primitive', () => {
    const root = mkdtempSync(join(tmpdir(), 'cal-002-quality-shadowed-undefined-'));
    const sourcePath = join(root, 'example.ts');
    try {
      writeFileSync(
        sourcePath,
        [
          "const undefined = 'AI generated this output';",
          "function emit(copy: string = 'Observable condition') { return { message: copy }; }",
          "export const exampleRule = { id: 'quality/example', description: 'Observable condition',",
          '  analyze() { return [emit(undefined)]; }',
          '};',
          '',
        ].join('\n'),
      );
      const emitted = collectPublicRuleCopy('quality/example', root)
        .map((entry) => entry.text)
        .join('\n');
      expect(emitted).toContain('AI generated this output');
      expect(() => assertQualityCopy(emitted, sourcePath)).toThrow(/provenance|authorship/i);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it('inspects strings returned by local message helpers', () => {
    const copy = collectPublicRuleCopy('security/dangerous-cors', RULE_SOURCE_ROOT);
    expect(copy.map((entry) => entry.text).join('\n')).toContain(
      'Reflective CORS: origin: true echoes the request origin.',
    );
  });

  it('represents mutable interpolations as runtime values instead of stale initializers', () => {
    const root = mkdtempSync(join(tmpdir(), 'cal-002-quality-mutable-copy-'));
    const sourcePath = join(root, 'example.ts');
    try {
      writeFileSync(
        sourcePath,
        [
          "export const exampleRule = { id: 'quality/example', description: 'Observable condition',",
          '  analyze() {',
          '    let dominant = 0;',
          '    dominant = 5;',
          '    return [{ message: `gap-${dominant}` }];',
          '  }',
          '};',
          '',
        ].join('\n'),
      );
      const emitted = collectPublicRuleCopy('quality/example', root)
        .map((entry) => entry.text)
        .join('\n');
      expect(emitted).toContain('gap-{runtime value}');
      expect(emitted).not.toContain('gap-0');
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it('fails closed when a shorthand parameter is overwritten before emission', () => {
    const root = mkdtempSync(join(tmpdir(), 'cal-002-quality-mutated-parameter-'));
    const sourcePath = join(root, 'example.ts');
    try {
      writeFileSync(
        sourcePath,
        [
          "import { externalMessage } from './external';",
          'function emit(message: string) {',
          '  message = externalMessage();',
          '  return { message };',
          '}',
          "export const exampleRule = { id: 'quality/example', description: 'Observable condition',",
          "  analyze() { return [emit('Safe outer copy')]; } };",
          '',
        ].join('\n'),
      );
      expect(() => collectPublicRuleCopy('quality/example', root)).toThrow(/cannot resolve public copy/i);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it('audits a complete escaped-pipe catalog description without scanning the ai/ rule ID', () => {
    const root = mkdtempSync(join(tmpdir(), 'cal-002-quality-copy-'));
    const catalogPath = join(root, 'catalog.md');
    try {
      writeFileSync(
        catalogPath,
        '| `ai/example` | low | on | ✓ | Observable prefix \\| LLMs wrote this suffix |\n',
      );
      const copy = collectGeneratedCatalogCopy('ai/example', catalogPath);
      expect(copy.text).toContain('Observable prefix | LLMs wrote this suffix');
      expect(() => assertQualityCopy(copy.text, copy.location)).toThrow(/provenance|authorship/i);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it('keeps all 73 quality-facing strings about observable quality only', () => {
    const qualityIds = canonicalAuthorityRowsV2()
      .filter((row) => row.sourceClass === 'starting-quality' || row.action === 'transfer')
      .map((row) => row.ruleId)
      .sort();
    expect(qualityIds).toHaveLength(73);
    expect(new Set(qualityIds).size).toBe(73);

    const failures: string[] = [];
    for (const ruleId of qualityIds) {
      const matchingRules = builtinRules.filter((candidate) => candidate.id === ruleId);
      expect(matchingRules, `${ruleId} runtime rule identity`).toHaveLength(1);
      collectFailure(failures, matchingRules[0]!.description ?? '', `${ruleId} runtime description`);
      expect(RULE_HINTS, `${ruleId} RULE_HINTS identity`).toHaveProperty(ruleId);
      const hint = RULE_HINTS[ruleId];
      expect(hint?.trim().length, `${ruleId} RULE_HINTS content`).toBeGreaterThan(0);
      collectFailure(failures, hint!, `${ruleId} RULE_HINTS`);
      for (const copy of collectPublicRuleCopy(ruleId, RULE_SOURCE_ROOT)) {
        collectFailure(failures, copy.text, copy.location);
      }
      const catalog = collectGeneratedCatalogCopy(ruleId, GENERATED_CATALOG);
      collectFailure(failures, catalog.text, catalog.location);
    }

    expect(failures, failures.join('\n')).toEqual([]);
  });
});
